# Default config values for CaloJetIDAnalyzer
import FWCore.ParameterSet.Config as cms

jetid = cms.EDAnalyzer(
    'CaloJetIDAnalyzer',
    useTracking          = cms.bool(True),
    requireRandomTrigger = cms.bool(False),
    bookAll              = cms.bool(False),
    bookDiJets           = cms.bool(True),
    bookByTrackJet       = cms.bool(True),
    book3rd              = cms.bool(True),
    bookTooMany          = cms.bool(True),
    avoidMuon            = cms.bool(False),
    srcTriggerResults    = cms.InputTag('TriggerResults::HLT'),
    srcTriggerEvent      = cms.InputTag('hltTriggerSummaryAOD::HLT'),
    srcPrimVertex        = cms.InputTag('offlinePrimaryVertices'),
    srcCaloJets          = cms.InputTag('caloEtaPt'),
    srcCaloJetTrkAssoc   = cms.InputTag('caloJTA'),
    srcTracks            = cms.InputTag('generalTracks'),
    srcTrackJets         = cms.InputTag('TrackJetsForJetID'),
    srcHCALnoiseRemoval  = cms.InputTag('hcalnoise'),
    jecTag               = cms.string(''),
    hltProcessName       = cms.string('HLT'),
    deltaRTrgMatch       = cms.double(0.1),
    triggerNames         = cms.vstring('HLT_L1Jet15:0.3',
                                       'HLT_Jet30',
                                       'HLT_Jet50',
                                       'HLT_Jet80',
                                       'HLT_Jet110',
                                       'HLT_Jet180',
                                       'HLT_Jet250'),
    max3rdJetPt          = cms.double(50.),
    maxDelta             = cms.double(0.6),
    maxTrackJetDeltaR    = cms.double(0.4),
    minMatchTrackPt      = cms.double(1.0),
    minTrackPt           = cms.double(1.0),
    requireProbe         = cms.bool(False),
    maxLeadEta           = cms.double(2.0),
    maxLeadDelta         = cms.double(0.5),
    minLeadDPhi          = cms.double(1.0),
    max4thJetPt          = cms.double(20),
    tooManyIs            = cms.uint32(6),
    minJetPt             = cms.double(20),
    mcXsecs              = cms.vdouble(5.156E+01, 9.475E-01, 4.004E-01, 9.487E-02,
                                       1.218E-02, 1.615E-03, 2.555E-04, 4.832E-05,
                                       1.061E-05, 2.631E-06, 7.212E-07, 2.409E-07,
                                       6.262E-08, 9.426E-09, 2.345E-09, 1.566E-10,
                                       1.379E-11, 1.297E-12, 1.139E-13, 8.420E-15,
                                       1.812E-16),
    ptHatBins            = cms.vdouble(0, 15, 20, 30, 50, 80, 120, 170, 230, 300,
                                       380, 470, 600, 800, 1000, 1400, 1800, 2200,
                                       2600, 3000, 3500, 999999),
    jetIDHelperConfig    = cms.PSet(useRecHits      = cms.bool(True),
                                    hbheRecHitsColl = cms.InputTag("hbhereco"),
                                    hoRecHitsColl   = cms.InputTag("horeco"),
                                    hfRecHitsColl   = cms.InputTag("hfreco"),
                                    ebRecHitsColl   = cms.InputTag("ecalRecHit",
                                                                   "EcalRecHitsEB"),
                                    eeRecHitsColl   = cms.InputTag("ecalRecHit",
                                                                   "EcalRecHitsEE")
                                    )
    )
