#include "TauAnalysis/RecoTools/plugins/PATTauPairEventSelector.h"

#include "PhysicsTools/UtilAlgos/interface/EventSelectorBase.h"

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecTauPairMinEventSelector, "PATElecTauPairMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATMuTauPairMinEventSelector, "PATMuTauPairMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATDiTauPairMinEventSelector, "PATDiTauPairMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecMuPairMinEventSelector, "PATElecMuPairMinEventSelector");

DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecTauPairMaxEventSelector, "PATElecTauPairMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATMuTauPairMaxEventSelector, "PATMuTauPairMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATDiTauPairMaxEventSelector, "PATDiTauPairMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecMuPairMaxEventSelector, "PATElecMuPairMaxEventSelector");

DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecTauPairCountEventSelector, "PATElecTauPairCountEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATMuTauPairCountEventSelector, "PATMuTauPairCountEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATDiTauPairCountEventSelector, "PATDiTauPairCountEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, PATElecMuPairCountEventSelector, "PATElecMuPairCountEventSelector");

