#include "TauAnalysis/RecoTools/plugins/ZllHypothesisT1T2EventSelector.h"

#include "CommonTools/UtilAlgos/interface/EventSelectorBase.h"

#include "FWCore/Framework/interface/MakerMacros.h"

using namespace reco;

DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisElecTauMinEventSelector, "ZllHypothesisElecTauMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisMuTauMinEventSelector, "ZllHypothesisMuTauMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisDiTauMinEventSelector, "ZllHypothesisDiTauMinEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisElecMuMinEventSelector, "ZllHypothesisElecMuMinEventSelector");

DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisElecTauMaxEventSelector, "ZllHypothesisElecTauMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisMuTauMaxEventSelector, "ZllHypothesisMuTauMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisDiTauMaxEventSelector, "ZllHypothesisDiTauMaxEventSelector");
DEFINE_EDM_PLUGIN(EventSelectorPluginFactory, ZllHypothesisElecMuMaxEventSelector, "ZllHypothesisElecMuMaxEventSelector");

