-- Metadata table
CREATE TABLE "METADATA" ( "NAME" VARCHAR2(4000), "TOKEN" VARCHAR2(4000) NOT NULL, "TIMETYPE" NUMBER(10) CONSTRAINT "METADATA_PK" PRIMARY KEY ( "NAME" ));
--grant select to public 
GRANT SELECT ON "METADATA" TO PUBLIC;
