
CONNECT CMS_ES_COMIS@cms_omds_lb/es164644


ALTER TABLE ECAL_TTCCI_CYCLE drop CONSTRAINT ecal_TTCCI_cycle_fk1;
ALTER TABLE ECAL_LTC_CYCLE drop CONSTRAINT ecal_LTC_cycle_fk1;
ALTER TABLE ECAL_LTS_CYCLE drop CONSTRAINT ecal_LTS_cycle_fk1;
ALTER TABLE ECAL_TTCF_CYCLE drop CONSTRAINT ecal_ttcf_cycle_fk1;
ALTER TABLE ECAL_SRP_CYCLE drop CONSTRAINT ecal_srp_cycle_fk1;


drop view  ES_CYCLE_VIEW;
drop view  ES_SCAN_CONFIGURATION;
drop view  ES_SEQUENCE;
drop view  ES_RUN_CONFIGURATION;

DROP TABLE ES_CCS_CYCLE;
DROP TABLE ES_DCC_CYCLE;
DROP TABLE ES_JBH4_CYCLE;
DROP TABLE ES_SCAN_CYCLE;
DROP TABLE ECAL_TTCCI_CYCLE;
DROP TABLE ECAL_LTC_CYCLE ;
DROP TABLE ECAL_LTS_CYCLE ;
DROP TABLE ECAL_ttcf_CYCLE ;
DROP TABLE ECAL_srp_CYCLE ;

DROP TABLE ES_CCS_CONFIGURATION;
DROP TABLE ES_DCC_CONFIGURATION;
DROP TABLE ECAL_TTCCI_CONFIGURATION;
DROP TABLE ECAL_LTC_CONFIGURATION ;
DROP TABLE ECAL_LTS_CONFIGURATION ;
DROP TABLE ES_JBH4_CONFIGURATION;
DROP TABLE ECAL_ttcf_CONFIGURATION ;
DROP TABLE ECAL_srp_CONFIGURATION ;
DROP TABLE ES_SCAN_DAT;


DROP TABLE ES_CYCLE_DAT;
DROP TABLE ES_SEQUENCE_DAT;
DROP TABLE ES_RUN_CONFIGURATION_DAT;


DROP TABLE ES_RUN_MODE_DEF;
DROP TABLE ES_SEQUENCE_TYPE_DEF;

DROP TABLE ES_DEAD_CHANNELS;

drop trigger es_run_mode_def_trg;
drop trigger es_sequence_type_def_trg
drop trigger es_sequence_dat_trg


DROP SEQUENCE es_run_mode_def_sq;
DROP SEQUENCE es_run_sq;
DROP SEQUENCE es_sequence_type_def_sq;
DROP SEQUENCE es_sequence_dat_sq;
DROP SEQUENCE es_cycle_dat_sq;
DROP SEQUENCE es_CCS_CONFIG_sq;
DROP SEQUENCE es_DCC_CONFIG_sq;
DROP SEQUENCE ecal_TTCCI_CONFIG_sq;
DROP SEQUENCE es_JBH4_CONFIG_sq; 
DROP SEQUENCE es_SCAN_CONFIG_sq; 

DROP SEQUENCE ecal_lts_CONFIG_sq; 
DROP SEQUENCE ecal_ltc_CONFIG_sq; 
DROP SEQUENCE ecal_ttcf_CONFIG_sq; 
DROP SEQUENCE ecal_srp_CONFIG_sq; 




@create_daq_ES_config


exit;


