#!/usr/bin/env perl

# -s slim
use Getopt::Std;
getopts('i:s');

if ($ARGV[0]) {
    $name = $ARGV[0];
} else {
    die "need a name for the tarfile\n";
}

$include  = "AnalysisDataFormats/HeavyFlavorObjects HeavyFlavorAnalysis/Lb2JpsiL0 HeavyFlavorAnalysis/Bs2MuMu/interface/HFMasses.hh";
if ($opt_i) {
    $include .= " $opt_i";
}

if ($opt_s) {$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/lib/\\*.so";}
$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/obj/\\*.o";
$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/test";
$exclude .= " --exclude HeavyFlavorAnalysis/Lb2JpsiL0/macros/obj/\\*.o";
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Lb2JpsiL0/macros/lib/\\*.so";}
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Lb2JpsiL0/macros/bin/\\*";}
$exclude .= " --exclude HeavyFlavorAnalysis/Lb2JpsiL0/test";
$exclude .= " --exclude HeavyFlavorAnalysis/Lb2JpsiL0/macros/batchruns";
$exclude .= " --exclude \\*.root";
$exclude .= " --exclude \\*.pdf";
$exclude .= " --exclude \\*.ps";
$exclude .= " --exclude \\*.eps";
$exclude .= " --exclude \\*Dict\\*";
$exclude .= " --exclude \\*CVS\\*";
$exclude .= " --exclude \\*.cvsignore\\*";
$exclude .= " --exclude \\*.admin\\*";
$exclude .= " --exclude \\*.DS_Store\\*";

system("tar zcvf $name $include $exclude"); 
print("tar zcvf $name $include $exclude  --wildcards\n"); 
