ALTER TABLE "CSCPEDESTALS" ADD "TIME" NUMBER(10) NOT NULL;
/* ALTER TABLE "CSCPEDESTALS" ADD "DATA_TAKING_TIME" DATE; */

ALTER TABLE "CSCGAINS" ADD "TIME" NUMBER(10) NOT NULL;
/* ALTER TABLE "CSCGAINS" ADD "DATA_TAKING_TIME" DATE; */

ALTER TABLE "CSCCROSSTALK" ADD "TIME" NUMBER(10) NOT NULL;
/* ALTER TABLE "CSCCROSSTALK" ADD "DATA_TAKING_TIME" DATE; */

ALTER TABLE "CSCNOISEMATRIX" ADD "TIME" NUMBER(10) NOT NULL;
/* ALTER TABLE "CSCNOISEMATRIX" ADD "DATA_TAKING_TIME" DATE; */
