CREATE TABLE CMS_XIEZHEN_DEV."IOV" ( "ID" NUMBER(10), CONSTRAINT "IOV_PK" PRIMARY KEY ( "ID" ) );

CREATE TABLE CMS_XIEZHEN_DEV."IOV_DATA" ( "POS" NUMBER(10) NOT NULL, "ID" NUMBER(10) NOT NULL, "IOV_TOKEN" VARCHAR2(4000) NOT NULL, "IOV_TIME" NUMBER(10) NOT NULL, CONSTRAINT "IOV_DATA_PK" PRIMARY KEY ( "ID","POS" ), CONSTRAINT "IOV_DATA_ID_FK" FOREIGN KEY ( "ID" ) REFERENCES CMS_XIEZHEN_DEV."IOV" ( "ID" ) );

