import FWCore.ParameterSet.Config as cms
import copy

from TauAnalysis.RecoTools.patPFTauSelection_cfi import *

selectedPatTausForWTauNuEta21 = copy.deepcopy(selectedPatTausEta21)
selectedPatTausForWTauNuPt20 = copy.deepcopy(selectedPatTausPt20)
selectedPatTausForWTauNuLeadTrk = copy.deepcopy(selectedPatTausLeadTrk)
selectedPatTausForWTauNuLeadTrkPt = copy.deepcopy(selectedPatTausLeadTrkPt)
selectedPatTausForWTauNuTaNCdiscr = copy.deepcopy(selectedPatTausTaNCdiscr)
selectedPatTausForWTauNuTrkIso = copy.deepcopy(selectedPatTausTrkIso)
selectedPatTausForWTauNuEcalIso = copy.deepcopy(selectedPatTausEcalIso)
selectedPatTausForWTauNuProng = copy.deepcopy(selectedPatTausProng)
selectedPatTausForWTauNuCharge = copy.deepcopy(selectedPatTausCharge)
selectedPatTausForWTauNuMuonVeto = copy.deepcopy(selectedPatTausMuonVeto)
selectedPatTausForWTauNuElectronVeto = copy.deepcopy(selectedPatTausElectronVeto)
selectedPatTausForWTauNuEcalCrackVeto = copy.deepcopy(selectedPatTausEcalCrackVeto)

selectedPatTausForWTauNuTaNCdiscrLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuTaNCdiscr)
selectedPatTausForWTauNuTrkIsoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuTrkIso)
selectedPatTausForWTauNuEcalIsoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuEcalIso)
selectedPatTausForWTauNuProngLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuProng)
selectedPatTausForWTauNuChargeLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuCharge)
selectedPatTausForWTauNuMuonVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuMuonVeto)
selectedPatTausForWTauNuElectronVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuElectronVeto)
selectedPatTausForWTauNuEcalCrackVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuEcalCrackVeto)



