import FWCore.ParameterSet.Config as cms
import copy

from TauAnalysis.RecoTools.patPFTauSelection_cfi import *

selectedPatTausForWTauNuEta21 = copy.deepcopy(selectedPatTausEta23)
selectedPatTausForWTauNuPt20 = copy.deepcopy(selectedPatTausPt20)
selectedPatTausForWTauNuLeadTrk = copy.deepcopy(selectedPatTausLeadTrk)
selectedPatTausForWTauNuLeadTrkPt = copy.deepcopy(selectedPatTausLeadTrkPt)
selectedPatTausForWTauNuTaNCdiscr = copy.deepcopy(selectedPatTausTaNCdiscr)
selectedPatTausForWTauNuTrkIso = copy.deepcopy(selectedPatTausTaNCdiscr)
selectedPatTausForWTauNuEcalIso = copy.deepcopy(selectedPatTausTaNCdiscr)
selectedPatTausForWTauNuProng = copy.deepcopy(selectedPatTausProng)
selectedPatTausForWTauNuCharge = copy.deepcopy(selectedPatTausCharge)
selectedPatTausForWTauNuMuonVeto = copy.deepcopy(selectedPatTausMuonVeto)
selectedPatTausForWTauNuElectronVeto = copy.deepcopy(selectedPatTausElectronVeto)
selectedPatTausForWTauNuEcalCrackVeto = copy.deepcopy(selectedPatTausEcalCrackVeto)

selectedPatTausForWTauNuLeadTrkPtLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuLeadTrkPt)
selectedPatTausForWTauNuTaNCdiscrLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuTaNCdiscr)
selectedPatTausForWTauNuTrkIsoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuTaNCdiscr)
selectedPatTausForWTauNuEcalIsoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuTaNCdiscr)
selectedPatTausForWTauNuProngLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuProng)
selectedPatTausForWTauNuChargeLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuCharge)
selectedPatTausForWTauNuMuonVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuMuonVeto)
selectedPatTausForWTauNuElectronVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuElectronVeto)
selectedPatTausForWTauNuEcalCrackVetoLooseIsolation = copy.deepcopy(selectedPatTausForWTauNuEcalCrackVeto)



