import FWCore.ParameterSet.Config as cms

isolhbherechitreflaggerJETMET = cms.EDProducer(
    'IsolatedHBHERecHitReflaggerJETMET',

    hbheInput = cms.InputTag('hbhereco'),
    ecalInputs = cms.VInputTag(cms.InputTag("ecalRecHit","EcalRecHitsEB"), cms.InputTag("ecalRecHit","EcalRecHitsEE")),
    trackInput = cms.InputTag('generalTracks'),
    metInput = cms.InputTag('met'),
    caloTowerInput = cms.InputTag('towerMaker'),

    # isolation cuts
    rbxMinE = cms.double(20.0),
    rbxMinHits = cms.int32(10),
    rbxMinTrkFidE = cms.double(10.0),
    rbxMaxHcalIsol = cms.double(0.05),
    rbxMaxEcalIsol = cms.double(0.05),
    rbxMaxTrackIsol = cms.double(0.05),
    hpdMinE = cms.double(30.0),
    hpdMinHits = cms.int32(3),
    hpdMinTrkFidE = cms.double(15.0),
    hpdMaxHcalIsol = cms.double(0.05),
    hpdMaxEcalIsol = cms.double(0.05),
    hpdMaxTrackIsol = cms.double(0.05),
    dihitMinE = cms.double(40.0),
    dihitMinTrkFidE = cms.double(20.0),
    dihitMaxHcalIsol = cms.double(0.05),
    dihitMaxEcalIsol = cms.double(0.05),
    dihitMaxTrackIsol = cms.double(0.05),
    monohitMinE = cms.double(50.0),
    monohitMinTrkFidE = cms.double(25.0),
    monohitMaxHcalIsol = cms.double(0.05),
    monohitMaxEcalIsol = cms.double(0.05),
    monohitMaxTrackIsol = cms.double(0.05),
    hbheFlagBit = cms.int32(31),

    # used by the object validator
    HBThreshold = cms.double(0.7),
    HESThreshold = cms.double(0.8),
    HEDThreshold = cms.double(0.8),
    EBThreshold = cms.double(0.07),
    EEThreshold = cms.double(0.3),
    HcalAcceptSeverityLevel = cms.uint32(9),
    EcalAcceptSeverityLevel = cms.uint32(1),
    UseHcalRecoveredHits = cms.bool(True),
    UseEcalRecoveredHits = cms.bool(False),
    MinValidTrackPt = cms.double(0.7),
    MinValidTrackPtBarrel = cms.double(1.0),
    MinValidTrackNHits = cms.int32(7),

    # track associator stuff
    TrackAssociatorParameters = cms.PSet(
    muonMaxDistanceSigmaX = cms.double(0.0),
    muonMaxDistanceSigmaY = cms.double(0.0),
    CSCSegmentCollectionLabel = cms.InputTag("cscSegments"),
    dRHcal = cms.double(9999.0),
    dREcal = cms.double(9999.0),
    CaloTowerCollectionLabel = cms.InputTag("towerMaker"),
    useEcal = cms.bool(True),
    dREcalPreselection = cms.double(0.05),
    HORecHitCollectionLabel = cms.InputTag("horeco"),
    dRMuon = cms.double(9999.0),
    trajectoryUncertaintyTolerance = cms.double(-1.0),
    crossedEnergyType = cms.string('SinglePointAlongTrajectory'),
    muonMaxDistanceX = cms.double(5.0),
    muonMaxDistanceY = cms.double(5.0),
    useHO = cms.bool(False),
    accountForTrajectoryChangeCalo = cms.bool(True),
    DTRecSegment4DCollectionLabel = cms.InputTag("dt4DSegments"),
    EERecHitCollectionLabel = cms.InputTag("ecalRecHit",
                                           "EcalRecHitsEE"),
    dRHcalPreselection = cms.double(0.2),
    useMuon = cms.bool(False),
    useCalo = cms.bool(True),
    EBRecHitCollectionLabel = cms.InputTag("ecalRecHit",
                                           "EcalRecHitsEB"),
    dRMuonPreselection = cms.double(0.2),
    usePreshower = cms.bool(False),
    dRPreshowerPreselection = cms.double(0.2),
    truthMatch = cms.bool(False),
    HBHERecHitCollectionLabel = cms.InputTag("hbhereco"),
    useHcal = cms.bool(True)
    ),
 )
