#!/bin/sh
G4SHARE=`scramv1 tool tag geant4 GEANT4_BASE`/share
G4Packaging=${G4SHARE}/physics_lists/hadronic/Packaging
G4THISLIB=${LOCALTOP}/${SCRAM_INTwork}/G4packaging
rm -rf $G4THISLIB
cp -rp ${G4Packaging} ${G4THISLIB}
mv ${G4THISLIB}/include/*.* ${G4THISLIB}/src
cp -p ${LOCALTOP}/src/SimG4Core/Packaging/src/*.* ${G4THISLIB}/src
mv ${G4THISLIB}/src/*.* ${LOCALTOP}/src/SimG4Core/Packaging/src
rm -fr ${G4THISLIB} 

