#!/bin/bash

export XDAQ_ROOT=/opt/xdaq
export XDAQ_OS=linux
export XDAQ_PLATFORM=x86_slc3

# Must be set to a local or networked root path
# This one is the copy on the .CMS private network
export ROOTSYS=/opt/root/current

export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/HLXReadOut/CoreUtils/lib/$XDAQ_OS/$XDAQ_PLATFORM:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/HLXReadOut/HLXCoreLibs/lib/$XDAQ_OS/$XDAQ_PLATFORM/:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/LumiDB/lib/$XDAQ_OS/$XDAQ_PLATFORM/:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/LumiCalc/lib/$XDAQ_OS/$XDAQ_PLATFORM/:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"

# Java
export PATH=$PATH:/usr/java/j2re-1.4.2_06/bin
