#!/bin/bash

export XDAQ_ROOT=/opt/xdaq
export XDAQ_OS=linux
export XDAQ_PLATFORM=x86_slc4

export ROOTSYS=/nfshome0/cmssw/slc4_ia32_gcc345/lcg/root/5.14.00g-CMS11

export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH=$ROOTSYS/bin:$PATH
export PATH=/usr/java/jdk1.5.0_09/bin:$PATH
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/HLXReadOut/CoreUtils/lib/$XDAQ_OS/$XDAQ_PLATFORM:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/HLXReadOut/HLXCoreLibs/lib/$XDAQ_OS/$XDAQ_PLATFORM:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/LumiDB/lib/$XDAQ_OS/$XDAQ_PLATFORM:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$BUILD_HOME/RecoLuminosity/LumiCalc/lib/$XDAQ_OS/$XDAQ_PLATFORM:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"

