#!/bin/bash

export DIPBASE=/opt/DIP/current
export CLASSPATH=$DIPBASE/lib/dip.jar
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DIPBASE/lib

# This is the DCS PC that forwards DIP data from the
# .CMS private network to the CERN network
export DIPNS=cms-cent-dcs-01

