# Python script generated by stageEnergy.py
# For Testbeam data processing

# Jamie Ballin, Imperial College London
# December 2008

import FWCore.ParameterSet.Config as cms

process = cms.Process("PROD")
process.load("RecoParticleFlow.PFAnalyses.pflowProcessTestbeam_cff")

# Files to process
runs = cms.untracked.vstring("rfio:///castor/cern.ch/cms/store/h2tb2006/reco/v6/h2.00030389.combined.OutServ_0.0-cmsswreco.root"

)

# Output tree of cleaned particles
process.TFileService.fileName = cms.string("outputtree_highEGeV_dirty.root")

# New Event file
process.finishup.fileName = cms.untracked.string("reprocessed_highEGeV_dirty.root")

process.particleFiltration.noiseMode = cms.bool(True)
process.extraction.saveJustPions = cms.bool(False)
process.extraction.applyCleaningCuts = cms.bool(False)
process.faketracks.justCreateEmptyCollections = cms.bool(True)
process.particleFlowRecHitHCAL.thresh_Barrel = cms.double(0.0)
process.particleFlowRecHitHCAL.thresh_Endcap = cms.double(0.0)
process.particleFlowRecHitHCAL.thresh_HF = cms.double(0.0)
process.particleFlowRecHitECAL.thresh_Barrel = cms.double(0.0)
process.particleFlowRecHitECAL.thresh_Endcap = cms.double(0.0)


process.maxEvents = cms.untracked.PSet(
    input=cms.untracked.int32(20000)
)
process.MessageLogger = cms.Service("MessageLogger",
    destinations=cms.untracked.vstring('cout')
)

process.source = cms.Source("PoolSource",
        fileNames = runs
)

process.p1 = cms.Path(process.pflowProcessTestbeam)

#process.outpath = cms.EndPath(process.finishup)
