# Python script generated by stageEnergy.py
# For Testbeam data processing

# Jamie Ballin, Imperial College London
# December 2008

import FWCore.ParameterSet.Config as cms

process = cms.Process("PROD")
process.load("RecoParticleFlow.PFAnalyses.pflowProcessTestbeam_cff")

from RecoParticleFlow.PFAnalyses.RunDict import *

from RecoParticleFlow.PFAnalyses.pflowOptions_cfi import *

outputTree = "outputtree_" + fileLabel
outputFile = "reprocessed_" + fileLabel
logFile = "log_" + str(options.beamEnergy) + "GeV" + options.fileSuffix + ".txt"


if options.notracks <> 0:
    process.faketracks.justCreateEmptyCollections = cms.bool(True)
    print "Running in notrack mode"

specifiedE = energies[options.beamEnergy]
result = map(lambda x : 'rfio:///castor/cern.ch/cms/store/h2tb2006/reco/v6/h2.000' + str(x) + '.combined.OutServ_0.0-cmsswreco.root', specifiedE)

if options.kevents <> 0:
    process.maxEvents = cms.untracked.PSet(
        input=cms.untracked.int32(options.kevents*1000)
        )

# Files to process
runs = cms.untracked.vstring(result)
print "Input files :"
print result

# Output tree of cleaned particles
process.TFileService.fileName = cms.string(outputTree)

# New Event file
process.finishup.fileName = cms.untracked.string(outputFile)

# LogFile

process.MessageLogger = cms.Service("MessageLogger",
    destinations=cms.untracked.vstring(logFile)
)

process.source = cms.Source("PoolSource",
        fileNames = runs
)

process.p1 = cms.Path(process.pflowProcessTestbeam)
#process.outpath = cms.EndPath(process.finishup)
