#include "Web.h"

using namespace std;
using namespace dqmevf;

void Web::setJCLogURL(std::string prochost, std::string procpid) {
  JCLogURL_ = prochost.substr(0,prochost.rfind(':'));
  cout << JCLogURL_ << endl;
  JCLogURL_+= ":9999/urn:xdaq-application:lid=10/ProcLog?log=/tmp/xdaqjcPID";
  JCLogURL_+= procpid + ".log";
}

void Web::importStaticJS(std::ostringstream *out, std::string uri) {

*out << endl;
*out << "var xmlhttp"									<<endl;
*out << "var xmlhttp1"									<<endl;
*out << "var xmlhttp2"									<<endl;
*out << "var xmlhttp3"									<<endl;
*out << "var xmlhttp4"									<<endl;
*out << "var process"									<<endl;
*out << "var theAppl"									<<endl;
*out << "var theBase"									<<endl;
*out << "var theUrl"									<<endl;
*out << "var thePage"									<<endl;
*out << "var msurl"									<<endl;
*out << "var updater"									<<endl;
*out << "var resetter"									<<endl;
*out << "var manualConfigure"								<<endl;
*out << "var manualEnable"								<<endl;
*out << "var manualHalt"								<<endl;
*out << "var nslaves"									<<endl;
*out << "var nslaveLast"								<<endl;
*out << "var pointer"									<<endl;
*out << "var flip"									<<endl;
*out << "var previousLs"								<<endl;
*out << "var lsCtr"									<<endl;
*out << ""										<<endl;
*out << "function bootstrap()								"<<endl;
*out << "{										"<<endl;
*out << "  pointer = 0									"<<endl;
*out << "  nslaves = 0									"<<endl;
*out << "  nslaveLast = 0								"<<endl;
*out << "  flip = 0									"<<endl;
*out << "  theAppl = location.href               					"<<endl;
*out << "  var c = theAppl.indexOf('html')						"<<endl;
*out << "  theUrl = theAppl.substring(0,c)       					"<<endl;
*out << "  theAppl = theAppl.substring(0,c-1)    					"<<endl;
*out << "  previousLs = 0 								"<<endl;
*out << "  lsCtr = 0									"<<endl;
*out << "										"<<endl;
*out << "  theBase='"<< uri <<"'                					"<<endl;
*out << "										"<<endl;
*out << "      msurl=theBase								"<<endl;
*out << "      updater=theBase								"<<endl;
*out << "      resetter=theBase								"<<endl;
*out << "      manualConfigure=theBase							"<<endl;
*out << "      manualEnable=theBase							"<<endl;
*out << "      manualHalt=theBase							"<<endl;
*out << "      if(theBase.lastIndexOf('/')==(msurl.length-1))				"<<endl;
*out << "      {									"<<endl;
*out << "	msurl += 'microState'	  						"<<endl;
*out << "	updater += 'updater'							"<<endl;
*out << "        document.getElementById('spot').setAttribute('href',theBase+'Spotlight')"<<endl;
*out << "	resetter += 'initiateReset'						"<<endl;
*out << "	manualConfigure+='manualConfigure'					"<<endl;
*out << "	manualEnable+='manualEnable'						"<<endl;
*out << "	manualHalt+='manualHalt'						"<<endl;
*out << "      }									"<<endl;
*out << "      else									"<<endl;
*out << "      {									"<<endl;
*out << "	msurl += '/microState'							"<<endl;
*out << "	updater += '/updater'							"<<endl;
*out << "        document.getElementById('spot').setAttribute('href',theBase+'/Spotlight')	"<<endl;
*out << "        updater += '/initiateReset'						"<<endl;
*out << "	manualConfigure+='/manualConfigure'					"<<endl;
*out << "	manualEnable+='/manualEnable'						"<<endl;
*out << "	manualHalt+='/manualHalt'						"<<endl;
*out << "      }									"<<endl;
*out << "      loadXMLDocStat()								"<<endl;
*out << "      loadXMLDocMSS()								"<<endl;
*out << "      banner()									"<<endl;
*out << "}										"<<endl;
*out << ""										<<endl;
*out << "function banner()								"<<endl;
*out << "{										"<<endl;
*out << "  if(document.getElementById('sysinfo'))					"<<endl;
*out << "  {										"<<endl;
*out << "    if(document.getElementById('st').innerHTML == 'Halted')			"<<endl;
*out << "      var sysinfo = document.getElementById('sysinfo').innerHTML		"<<endl;
*out << "    else									"<<endl;
*out << "      var sysinfo = document.getElementById('loads').innerHTML			"<<endl;
*out << "    document.getElementById('sys1').innerHTML=document.getElementById('sysinfo').innerHTML	"<<endl;
*out << "    document.getElementById('sys2').innerHTML=document.getElementById('loads').innerHTML	"<<endl;
*out << "  }										"<<endl;
*out << "  setTimeout('banner()',100)							"<<endl;
*out << "}										"<<endl;
*out << ""										<<endl;
*out << "function loadXMLDocMSS()							"<<endl;
*out << "{										"<<endl;
*out << "  xmlhttp=null									"<<endl;
*out << "  										"<<endl;
*out << "  if (window.XMLHttpRequest) 							"<<endl;
*out << "    {										"<<endl;
*out << "      xmlhttp=new XMLHttpRequest()						"<<endl;
*out << "    } 										"<<endl;
*out << "  else if (window.ActiveXObject)						"<<endl;
*out << "    { 										"<<endl;
*out << "      xmlhttp=new ActiveXObject('Microsoft.XMLHTTP') 				"<<endl;
*out << "    } 										"<<endl;
*out << "  if (xmlhttp!=null) 								"<<endl;
*out << "    {										"<<endl;
*out << "      xmlhttp.onreadystatechange=ParseMSReply 					"<<endl;
*out << "										"<<endl;
*out << "      xmlhttp.open('GET',msurl ,true) 						"<<endl;
*out << "										"<<endl;
*out << "      xmlhttp.send(null) 							"<<endl;
*out << "										"<<endl;
*out << "      setTimeout('loadXMLDocMSS()',1000)					"<<endl;
*out << "										"<<endl;
*out << "    } 										"<<endl;
*out << "  else 									"<<endl;
*out << "    {										"<<endl;
*out << "      alert('Your browser does not support XMLHTTP.') 				"<<endl;
*out << "    } 										"<<endl;
*out << "} 										"<<endl;
*out << ""										<<endl;
*out << "function loadXMLDocStat()							"<<endl;
*out << "{										"<<endl;
*out << "  if (window.XMLHttpRequest) 							"<<endl;
*out << "    {										"<<endl;
*out << "      xmlhttp2=new XMLHttpRequest()						"<<endl;
*out << "    } 										"<<endl;
*out << "  else if (window.ActiveXObject)						"<<endl;
*out << "    { 										"<<endl;
*out << "      xmlhttp2=new ActiveXObject('Microsoft.XMLHTTP') 				"<<endl;
*out << "    } 										"<<endl;
*out << "  if (xmlhttp2!=null) 								"<<endl;
*out << "    {										"<<endl;
*out << "      xmlhttp2.onreadystatechange=ParseStatReply 				"<<endl;
*out << "      xmlhttp2.open('GET',updater ,true) 					"<<endl;
*out << "      xmlhttp2.send(null) 							"<<endl;
*out << "      setTimeout('loadXMLDocStat()',5000)					"<<endl;
*out << "    } 										"<<endl;
*out << "  else { alert('Your browser does not support XMLHTTP.')} 			"<<endl;
*out << "} 										"<<endl;
*out << "                                                                               "<<endl;
*out << "function callReset(usepid)							"<<endl;
*out << "{										"<<endl;
*out << "  document.getElementById('ResetButton'+usepid).innerHTML='Resetting'		"<<endl;
*out << "  document.getElementById('ResetButton'+usepid).setAttribute('onclick','')	"<<endl;
*out << "  document.getElementById('ResetButton'+usepid).setAttribute('hidden','hidden')"<<endl;
*out << "  if (window.XMLHttpRequest) 							"<<endl;
*out << "  {										"<<endl;
*out << "    xmlhttp3=new XMLHttpRequest()						"<<endl;
*out << "  } 										"<<endl;
*out << "  else if (window.ActiveXObject)						"<<endl;
*out << "  { 										"<<endl;
*out << "    xmlhttp3=new ActiveXObject('Microsoft.XMLHTTP') 				"<<endl;
*out << "  } 										"<<endl;
*out << "  if (xmlhttp3!=null) 								"<<endl;
*out << "  {										"<<endl;
*out << "    xmlhttp3.onreadystatechange=ParseResetReply 				"<<endl;
*out << "    xmlhttp3.open('GET',resetter+'?pid='+usepid ,true) 			"<<endl;
*out << "    xmlhttp3.send(null) 							"<<endl;
*out << "  } 										"<<endl;
*out << "  else { alert('Your browser does not support XMLHTTP.') }			"<<endl;
*out << "}										"<<endl;
*out << ""										<<endl;
*out << "function callManual(cmd)                                                       "<<endl;
*out << "{                                                                              "<<endl;
*out << "  if (window.XMLHttpRequest)                                                   "<<endl;
*out << "  {                                                                            "<<endl;
*out << "    xmlhttp4=new XMLHttpRequest()                                              "<<endl;
*out << "  }                                                                            "<<endl;
*out << "  else if (window.ActiveXObject)                                               "<<endl;
*out << "  {                                                                            "<<endl;
*out << "    xmlhttp4=new ActiveXObject('Microsoft.XMLHTTP')                            "<<endl;
*out << "  }                                                                            "<<endl;
*out << "  if (xmlhttp4!=null)                                                          "<<endl;
*out << "  {                                                                            "<<endl;
*out << "    if (cmd == 0 ){								"<<endl;
*out << "      xmlhttp4.open('GET',manualConfigure ,true)                               "<<endl;
*out << "      xmlhttp4.send(null)                                                      "<<endl;
*out << "    }										"<<endl;
*out << "    else if (cmd == 1){							"<<endl;
*out << "      xmlhttp4.open('GET',manualEnable ,true)                                  "<<endl;
*out << "      xmlhttp4.send(null)                                                      "<<endl;
*out << "    }										"<<endl;
*out << "    else if (cmd == 2){							"<<endl;
*out << "      xmlhttp4.open('GET',manualHalt ,true)                                    "<<endl;
*out << "      xmlhttp4.send(null)                                                      "<<endl;
*out << "    }										"<<endl;
*out << "  }                                                                            "<<endl;
*out << "  else { alert('Your browser does not support XMLHTTP.') }                     "<<endl;
*out << "}										"<<endl;
*out << ""										<<endl;
*out << "function ParseMSReply() 							"<<endl;
*out << "{ 										"<<endl;
*out << "  if (xmlhttp.readyState==4) 							"<<endl;
*out << "  { 										"<<endl;
*out << "										"<<endl;
*out << "    if (xmlhttp.status==200) 							"<<endl;
*out << "    { 										"<<endl;
*out << "      document.getElementById('msBody').innerHTML=xmlhttp.responseText 	"<<endl;
*out << "      var i = 0								"<<endl;
*out << "      var pid 									"<<endl;
*out << "/*i										"<<endl;
*out << "	while(pid=document.getElementById('p'+i) && i<32)			"<<endl;
*out << " 	{									"<<endl;
*out << "	  var active =  document.getElementById('a'+i)				"<<endl;
*out << "	  var link =  document.getElementById('pl'+i)				"<<endl;
*out << "	  //var href = pid.getAttribute('href');				"<<endl;
*out << "	  if(!link) continue							"<<endl;
*out << "	  //if(active.innerHTML=='Alive')					"<<endl;
*out << "	  //{									"<<endl;
*out << "	   //  pid.setAttribute('href',theBase+href);				"<<endl;
*out << "	   //  link.setAttribute('href',theBase+'SubWeb?process='+pid.innerHTML+'&method=Spotlight')"<<endl;
*out << "	   //  link.innerHTML = pid.innerHTML					"<<endl;
*out << "          //}									"<<endl;
*out << "	  //else								"<<endl;
*out << "	  //{									"<<endl;
*out << "	     //link.removeAttribute('href')					"<<endl;
*out << "	     //link.innerHTML = pid.innerHTML					"<<endl;
*out << "	  //}									"<<endl;
*out << "	  i++									"<<endl;
*out << "	}									"<<endl;
*out << "*/										"<<endl;
*out << "    }										"<<endl;
*out << "    else 									"<<endl;
*out << "    { 										"<<endl;
*out << "      document.getElementById('msBody').innerHTML=xmlhttp.statusText		"<<endl;
*out << "    } 										"<<endl;
*out << "  }										"<<endl;
*out << "} 										"<<endl;
*out << "                                                                               "<<endl;
*out << "function ParseResetReply() 							"<<endl;
*out << "{										"<<endl;
*out << "}										"<<endl;
*out << "                                                                               "<<endl;
*out << "function ParseStatReply() 							"<<endl;
*out << "{ 										"<<endl;
*out << "  if (xmlhttp2.readyState==4) 							"<<endl;
*out << "  { 										"<<endl;
*out << "										"<<endl;
*out << "    if (xmlhttp2.status==200) 							"<<endl;
*out << "    {										"<<endl;
*out << "      //copy response to a div 						"<<endl;
*out << "      var trick = document.getElementById('s3').innerHTML=xmlhttp2.responseText"<<endl;
*out << "      var trickID = document.getElementById('s3')				"<<endl;
*out << "      document.getElementById('className').innerHTML='<b>'+document.getElementById('cl').innerHTML+'</b>'"<<endl;
*out << "      document.getElementById('instance').innerHTML=document.getElementById('in').innerHTML		"<<endl;
*out << "      document.getElementById('stateName').innerHTML=document.getElementById('st').innerHTML		"<<endl;
*out << "      document.getElementById('runNumber').innerHTML=document.getElementById('ru').innerHTML		"<<endl;
*out << "      document.getElementById('CMSSWConfiguration').innerHTML=document.getElementById('hlt').innerHTML	"<<endl;
*out << "      document.getElementById('version').innerHTML=document.getElementById('ve').innerHTML		"<<endl;
*out << "      ///document.getElementById('shmem').innerHTML=document.getElementById('sh').innerHTML		"<<endl;
*out << "//    document.getElementById('msl').innerHTML=document.getElementById('ms').innerHTML			"<<endl;
*out << "      document.getElementById('nslave').innerHTML=document.getElementById('nsl').innerHTML		"<<endl;
*out << "      document.getElementById('log').innerHTML=document.getElementById('lg').innerHTML			"<<endl;
*out << "										"<<endl;
*out << "      //update microstate table layout if number of slaves is changed		"<<endl;
*out << "      nslaves=document.getElementById('nsl').innerHTML				"<<endl;
*out << "      var mstableElement=document.getElementById('msTable')			"<<endl;
*out << "      var msbodyElement = document.getElementById('msBody')			"<<endl;
*out << "      var i = 0								"<<endl;
*out << "      var mstr									"<<endl;
*out << "      var pl									"<<endl;
*out << "      while (i<nslaves) {							"<<endl;
*out << "          mstr='msTr'+i							"<<endl;
*out << "          pl = 'pl'+i								"<<endl;
*out << "          if (!document.getElementById(mstr)) {						"<<endl;
*out << "            msbodyElement.innerHTML +='<tr id=\"msTr'+i+'\"><td><a id=\"'+pl+'\"></td></tr>' 	"<<endl;
*out << "          }									"<<endl;
*out << "          i++									"<<endl;
*out << "      }									"<<endl;
*out << "        //delete if it decreased..						"<<endl;
*out << "      if (nslaves<nslaveLast) {						"<<endl;
*out << "          while (i<nslaveLast) {						"<<endl;
*out << "            mstr='msTr'+i							"<<endl;
*out << "            var oldtr = document.getElementById(mstr)				"<<endl;
*out << "            msBodyElement.removeChild(oldtr)					"<<endl;
*out << "            i++								"<<endl;
*out << "          }									"<<endl;
*out << "      }									"<<endl;
*out << "      nslaveLast=nslaves							"<<endl;
*out << "         									"<<endl;
*out << "										"<<endl;
*out << "    }										"<<endl;
*out << "     										"<<endl;
*out << "    else 									"<<endl;
*out << "    { 										"<<endl;
*out << "      document.getElementById('msBody').innerHTML=xmlhttp2.statusText		"<<endl;
*out << "      document.getElementById('stateName').innerHTML=xmlhttp2.statusText	"<<endl;
*out << "    } 										"<<endl;
*out << "  }										"<<endl;
*out << "}										"<<endl;
*out << ""<<endl;

}


void Web::importStaticHTML(std::ostringstream *out, std::string uri) {

*out << "<!-- base href=\"/urn:xdaq-application:lid=50\"> -->"<<endl;
*out << "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"<<endl;
*out << "<html>"<<endl;
*out << "  <head>"<<endl;
*out << "    <script>"<<endl;
importStaticJS(out,uri);
*out << "    </script>"<<endl;
*out << "    <style type=\"text/css\">"<<endl;
*out << "      #s1 {border-width: 2px; border: solid blue; text-align: right; background: lightgrey; font-size: 9pt}"<<endl;
*out << "      #s2 {border-width: 2px; border: white; text-align: left; vertical-align: top; background: green; font-size: 12pt; height:112; width:80 }";
*out << endl;
*out << "    </style>"<<endl;
*out << "    <link type=\"text/css\" rel=\"stylesheet\" href=\"/evf/html/styles.css\"/>"<<endl;
*out << "    <title style=\"font-family: fantasy, cursive, Serif;\">dqmevf::Processor  0.9 </title>"<<endl;
*out << "  </head>"<<endl;
*out << "  <body onload=\"bootstrap()\">"<<endl;
*out << "    <div id=\"s3\"  height=\"0\" width=\"0\" style=\"font-size:0\"></div>"<<endl;
*out << "    <div type=\"hidden\" id=\"s4\"  height=\"0\" width=\"0\" style=\"font-size:0\"></div>"<<endl;
*out << "    <table border=\"0\" width=\"100%\">"<<endl;
*out << "      <!-- upper interface row -->	"<<endl;
*out << "      <tr>"<<endl;
*out << "        <!-- icon -->"<<endl;
*out << "        <td align=\"left\">"<<endl;
*out << "        <a href=\""<< JCLogURL_ << "\">"<<endl;
*out << "	   <img id=\"icon\" align=\"middle\" src=\"/evf/images/metal029.jpg\" alt=\"main\" width=\"64\" height=\"64\">" << endl;
*out << "        </a>"<<endl;
*out << "        </td>"<<endl;
*out << "        <!-- Application info -->"<<endl;
*out << "        <td align=\"middle\">"<<endl;
*out << "          <table style=\"font-size:12pt\">"<<endl;
*out << "            <tr><td id=\"className\"></td><td align=\"right\" id=\"instance\"></td></tr>"<<endl;
*out << "            <tr><td><b>State:</b><td align=\"right\" id=\"stateName\"></td></tr>"<<endl;
*out << "            <tr><td><b>Run Number:<b></td><td align=\"right\" id=\"runNumber\"></td></tr>"<<endl;
*out << "            <tr><td align=\"left\" colspan=\"2\" id=\"CMSSWConfiguration\"></td><td/></tr>"<<endl;
*out << "          </table>"<<endl;
*out << "        </td>"<<endl;
*out << "        <!-- subprocess state -->"<<endl;
*out << "        <td align=\"middle\">"<<endl;
*out << "	   <table id=\"msTable\">"<<endl;
*out << "	     <thead style=\"color:white; background-color:black\">"<<endl;
*out << "	       <tr>"<<endl;
*out << "	         <th width=\"25\">xState</th>"<<endl;
*out << "	         <th width=\"8\">Role</th>"<<endl;
*out << "	         <th width=\"25\">pid</th>"<<endl;
*out << "	         <th width=\"25\">EPState</th>"<<endl;
*out << "	         <th width=\"25\">LastModule</th>"<<endl;
*out << "	         <th width=\"35\">Accepted/Processed(%)</th>"<<endl;
*out << "	         <th width=\"15\">LS</th>"<<endl;
*out << "	       </tr>"<<endl;
*out << "	     </thead>"<<endl;
*out << "	     <tbody id=\"msBody\">"<<endl;
*out << "	     </tbody>"<<endl;
*out << "	   </table> "<<endl;
*out << "	 </td> "<<endl;
*out << "        <!-- static links.. -->"<<endl;
*out << "        <td width=\"32\">"<<endl;
*out << "          <a href=\"/urn:xdaq-application:lid=3\">"<<endl;
*out << "            <img align=\"middle\" src=\"/hyperdaq/images/HyperDAQ.jpg\" alt=\"HyperDAQ\" width=\"32\" height=\"32\">"<<endl;
*out << "          </a>"<<endl;
*out << "        </td>"<<endl;
*out << "        <td width=\"32\">"<<endl;
*out << "          <a id=\"spot\" href=\"/Spotlight\">"<<endl;
*out << "            <img align=\"middle\" src=\"/evf/images/spoticon.jpg\" alt=\"debug\" width=\"32\" height=\"32\">"<<endl;
*out << "          </a>"<<endl;
*out << "        </td>"<<endl;
*out << "      </tr>"<<endl;
*out << "      <tr>"<<endl;
*out << "        <!-- sys Application version -->"<<endl;
*out << "        <td align=\"right\"><b>Version</b></td>"<<endl;
*out << "        <td id=\"version\">"<<endl;
*out << "        </td>"<<endl;
*out << "      </tr>"<<endl;
*out << "    </table>"<<endl;
*out << "    <hr>"<<endl;
*out << "      <table>"<<endl;
*out << "        <!-- sys scroller -->"<<endl;
*out << "        <tr valign=\"top\">"<<endl;
*out << "          <td colspan=3>"<<endl;
*out << "            <textarea rows=10 cols=80 scroll=yes id=\"log\" readonly title=\"Last Log Messages\">"<<endl;
*out << "            </textarea>"<<endl;
*out << "          </td>"<<endl;
*out << "          <td>"<<endl;
*out << "            <table frame=\"void\" rules=\"groups\" class=\"states\">"<<endl;
*out << "              <colgroup align=\"right\">"<<endl;
*out << "              <tr>"<<endl;
*out << "                <td>Slave Processes</td>"<<endl;
*out << "                <td id=\"nslave\"></td>"<<endl;
*out << "              </tr>"<<endl;
*out << "           </table>"<<endl;
*out << "         </td>"<<endl;
*out << "       </tr>"<<endl;
*out << "       <tr>"<<endl;
*out << "         <td  colspan=\"3\" id=\"sys\">"<<endl;
*out << "           <table style=\"color:white; background-color:black\"><tr id=\"sys1\"><td></td></tr><tr><td id=\"sys2\"></td></tr></table>"<<endl;
*out << "         </td>"<<endl;
*out << "       </tr>"<<endl;
*out << "     </table>"<<endl;
*out << " </body>"<<endl;
*out << "</html>"<<endl;

}
