#!/bin/bash
#Outputs code to copy and paste into TestbeamPreprocess.C for all currently staged runs.
stager_qry -M /castor/cern.ch/cms/store/h2tb2006/reco/v6/ | grep  STAGED | awk -F. '{print "\"rfio://"$1"."$2"."$3"."$4"."$5"."$6".root\", "}'
