#include "TauAnalysis/CandidateTools/plugins/VBFDiCandidatePairEventSelector.h"

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_FWK_MODULE(DiCandidatePairVBFEventSelector);
DEFINE_FWK_MODULE(PATElecTauPairVBFEventSelector);
DEFINE_FWK_MODULE(PATMuTauPairVBFEventSelector);
DEFINE_FWK_MODULE(PATDiTauPairVBFEventSelector);
DEFINE_FWK_MODULE(PATElecMuPairVBFEventSelector);
DEFINE_FWK_MODULE(PATDiElecPairVBFEventSelector);
DEFINE_FWK_MODULE(PATDiMuPairVBFEventSelector);

DEFINE_FWK_MODULE(DiCandidatePairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATElecTauPairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATMuTauPairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATDiTauPairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATElecMuPairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATDiElecPairVBFEventRefSelector);
DEFINE_FWK_MODULE(PATDiMuPairVBFEventRefSelector);
