import FWCore.ParameterSet.Config as cms
from ElectroWeakAnalysis.MultiBosons.kinAxis_cfi  import *

VgAnalyzerKit = cms.EDProducer("VgAnalyzerKit",
                               ntuplize = cms.string('none'),
                               outputTextName = cms.string('VgAnalyzerKit_output.txt'),
                               enable = cms.string(''),
                               disable = cms.string(''),
                               doMuon         = cms.bool(True),
                               doElectron     = cms.bool(True),
                               doTau          = cms.bool(True),
                               doJet          = cms.bool(True),
                               doMET          = cms.bool(True),
                               doPhoton       = cms.bool(True),
                               doTrack        = cms.bool(True),
                               doGenParticles = cms.bool(True),
                               doStoreJets    = cms.bool(False),
                               doSkim         = cms.bool(True),
                               doZmumu        = cms.bool(False),
                               electronSrc = cms.InputTag("cleanPatElectrons"),
                               tauSrc = cms.InputTag("cleanPatTaus"),
                               muonSrc = cms.InputTag("cleanPatMuons"),
                               jetSrc = cms.InputTag("cleanPatJets"),
                               photonSrc = cms.InputTag("cleanPatPhotons"),
                               METSrc = cms.InputTag("patMETs"),
                               trackSrc = cms.InputTag("allTrackCandidates"),
                               genParticleSrc = cms.InputTag("genParticles"),
                               zmumuSrc = cms.InputTag("dimuonsGlobal"),
                               L1GTReadoutRecord =cms.InputTag("hltGtDigis"),
                               #triggerResults = cms.InputTag("TriggerResults::HLT"),
                               #triggerResults = cms.InputTag("TriggerResults::REDIGI37X"),
                               triggerResults = cms.InputTag("TriggerResults::REDIGI36X"),
                               triggerEvent = cms.InputTag("patTriggerEvent"),
                               GTDigiLabel = cms.InputTag("gtDigis"),
                               VtxLabel = cms.InputTag("offlinePrimaryVertices"),
                               CaloTowerLabel = cms.InputTag("towerMaker"),
                               TrackLabel = cms.InputTag("generalTracks"),
                               #tcMETLabel = cms.InputTag("tcMet"),
                               #pfMETLabel = cms.InputTag("pfMet"),
                               tcMETLabel = cms.InputTag("patMETsTC"),
                               pfMETLabel = cms.InputTag("patMETsPF"),
                               LeadingElePtCut = cms.double(15),
                               LeadingMuPtCut = cms.double(15),
                               LeadingPhoPtCut = cms.double(10),
                               ebReducedRecHitCollection = cms.InputTag("reducedEcalRecHitsEB"),
                               eeReducedRecHitCollection = cms.InputTag("reducedEcalRecHitsEE"),
                               BeamSpotCollection = cms.InputTag("offlineBeamSpot"),
                               muonAxis     = kinAxis(0, 200, 0, 200),
                               electronAxis = kinAxis(0, 200, 0, 200),
                               tauAxis      = kinAxis(0, 200, 0, 200),
                               jetAxis      = kinAxis(0, 200, 0, 200),
                               METAxis      = kinAxis(0, 200, 0, 200),
                               photonAxis   = kinAxis(0, 200, 0, 200),
                               trackAxis    = kinAxis(0, 200, 0, 200),
                               genParticleAxis = kinAxis(0, 200, 0, 200)
                               )


