# Auto generated configuration file
# using: 
# Revision: 1.155 
# Source: /cvs_server/repositories/CMSSW/CMSSW/Configuration/PyReleaseValidation/python/ConfigBuilder.py,v 
# with command line options: harvest -s HARVESTING:dqmHarvesting -n -1 --conditions MC_3XY_V9A::All --filein file:RecoOutput.root --python_filename Harvesting_cfg.py --no_exec
import FWCore.ParameterSet.Config as cms

process = cms.Process('HARVESTING')

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.StandardSequences.MixingNoPileUp_cff')
process.load('Configuration.StandardSequences.GeometryExtended_cff')
process.load('Configuration.StandardSequences.MagneticField_38T_cff')
process.load('Configuration.StandardSequences.EDMtoMEAtRunEnd_cff')
process.load('Configuration.StandardSequences.Harvesting_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
process.load('Configuration.EventContent.EventContent_cff')

process.configurationMetadata = cms.untracked.PSet(
    version = cms.untracked.string('$Revision: 1.155 $'),
    annotation = cms.untracked.string('harvest nevts:100'),
    name = cms.untracked.string('PyReleaseValidation')
)
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)
process.options = cms.untracked.PSet(
    Rethrow = cms.untracked.vstring('ProductNotFound'),
    fileMode = cms.untracked.string('FULLMERGE')
)
# Input source
process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring('file:valid_reco.root'),
    processingMode = cms.untracked.string('RunsAndLumis')
)

# Additional output definition

# Other statements
process.GlobalTag.globaltag = 'MC_3XY_V9A::All'

# Path and EndPath definitions
process.edmtome_step = cms.Path(process.EDMtoME)
process.validationpreprodHarvesting = cms.Path(process.postValidation*process.hltpostvalidation_preprod)
process.validationprodHarvesting = cms.Path(process.postValidation*process.hltpostvalidation_prod)
process.dqmHarvesting = cms.Path(process.DQMOffline_SecondStep*process.DQMOffline_Certification)
process.validationHarvesting = cms.Path(process.postValidation*process.hltpostvalidation)
process.validationHarvestingFS = cms.Path(process.HarvestingFastSim)
process.dqmHarvestingPOG = cms.Path(process.DQMOffline_SecondStep_PrePOG)
process.dqmsave_step = cms.Path(process.DQMSaver)

# Schedule definition
process.schedule = cms.Schedule(process.edmtome_step,process.dqmHarvesting,process.dqmsave_step)

#-----------------------------------------------------------------------------------
# Mark's changes start (everything above this point is the output from cmsDriver)
#

# For some reason a seed harvester isn't included in the standard sequences. If this next processor isn't
# run then things like efficiencies are just added together instead of recalculated.
process.postProcessorSeed = cms.EDAnalyzer("DQMGenericClient",
	profile = cms.vstring(),
	resolution = cms.vstring(),
	efficiency = cms.vstring("effic \'Efficiency vs #eta\' num_assoc(simToReco)_eta num_simul_eta", 
		"efficPt \'Efficiency vs p_{T}\' num_assoc(simToReco)_pT num_simul_pT", 
		"fakerate \'Fake rate vs #eta\' num_assoc(recoToSim)_eta num_reco_eta fake", 
		"fakeratePt \'Fake rate vs p_{T}\' num_assoc(recoToSim)_pT num_reco_pT fake" ),
	subDirs = cms.untracked.vstring('Tracking/Seed/*'),
	outputFileName = cms.untracked.string('')
)

process.dqmSaver.saveByRun = -1
process.dqmSaver.saveAtJobEnd = True
process.dqmSaver.forceRunNumber = 1

# Remove the HLT harvesting from the validation harvesting step
process.validationHarvesting = cms.Path(process.postValidation)
process.trackingOnlyHarvesting = cms.Path(process.postProcessorTrack)
process.seedingOnlyHarvesting = cms.Path(process.postProcessorSeed)
#process.schedule = cms.Schedule(process.edmtome_step,process.validationHarvesting,process.dqmsave_step)
process.schedule = cms.Schedule(process.edmtome_step,process.trackingOnlyHarvesting,process.seedingOnlyHarvesting,process.dqmsave_step)
#process.schedule = cms.Schedule(process.edmtome_step,process.seedingOnlyHarvesting,process.dqmsave_step)

#process.source.fileNames = cms.untracked.vstring("file:valid_reco.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu0/valid_reco.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu5/valid_reco_10_1.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu25/valid_reco_10_1.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/muon/10muon_pu50/valid_reco_10_1.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_10_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_11_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_12_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_13_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_14_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_15_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_16_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_17_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_18_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_19_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_20_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_21_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_22_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_23_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_24_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_25_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_26_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_27_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_28_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_29_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu0/valid_reco_30_1.root")
#process.source.fileNames = cms.untracked.vstring( #"file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_10_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_11_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_12_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_13_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_14_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_15_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_16_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_17_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_18_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_19_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_20_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_21_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_22_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_23_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_24_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_25_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_26_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_27_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_28_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu5/valid_reco_29_1.root")
#process.source.fileNames = cms.untracked.vstring(
##"file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_6_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_10_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_11_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_12_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_13_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_14_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_15_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_16_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_17_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_18_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_19_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_20_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_21_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_22_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_23_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_24_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_25_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_26_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_27_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_28_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_29_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu25/valid_reco_30_1.root")
#process.source.fileNames = cms.untracked.vstring("file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_1_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_2_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_4_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_5_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_6_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_7_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_8_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_9_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_10_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_11_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_12_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_13_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_14_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_15_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_16_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_17_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_18_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_19_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_20_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_21_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_22_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_23_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_24_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_25_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_26_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_27_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_28_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_29_1.root")
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_30_1.root")
process.source.fileNames = cms.untracked.vstring(
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_1_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_2_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_3_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_4_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_5_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_6_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_7_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_8_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_9_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_10_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_11_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_12_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_13_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_14_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_15_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_16_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_17_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_18_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_19_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_20_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_21_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_22_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_23_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_24_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_25_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_26_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_27_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_28_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_29_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_30_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_31_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_32_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_33_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_34_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_35_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_36_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_37_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_38_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_39_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_40_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_41_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_42_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_43_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_44_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_45_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_46_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_47_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_48_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_49_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_50_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_51_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_52_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_53_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_54_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_55_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_56_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_57_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_58_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_59_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_60_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_61_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_62_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_63_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_64_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_65_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_66_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_67_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_68_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_69_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_70_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_71_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_72_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_73_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_74_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_75_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_76_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_77_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_78_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_79_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_80_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_81_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_82_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_83_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_84_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_85_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_86_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_87_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_88_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_89_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_90_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_91_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_92_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_93_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_94_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_95_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_96_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_97_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_98_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_99_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_100_1.root",
##corrupted    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_101_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_102_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_103_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_104_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_105_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_106_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_107_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_108_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_109_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_110_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_111_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_112_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_113_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_114_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_115_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_116_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_117_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_118_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_119_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_120_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_121_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_122_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_123_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_124_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_125_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_126_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_127_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_128_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_129_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_130_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_131_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_132_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_133_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_134_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_135_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_136_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_137_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_138_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_139_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_140_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_141_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_142_1.root",
##corrupted    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_143_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_144_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_145_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_146_1.root",
##corrupted    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_147_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_148_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_149_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_150_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_151_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_152_1.root",
#    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_153_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_154_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_155_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_156_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_157_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_158_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_159_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_160_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_161_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_162_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_163_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_164_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_165_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_166_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_167_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_168_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_169_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_170_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_171_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_172_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_173_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_174_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_175_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_176_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_177_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_178_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_179_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_180_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_181_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_182_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_183_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_184_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_185_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_186_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_187_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_188_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_189_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_190_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_191_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_192_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_193_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_194_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_195_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_196_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_197_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_198_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_199_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_200_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_201_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_202_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_203_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_204_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_205_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_206_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_207_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_208_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_209_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_210_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_211_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_212_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_213_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_214_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_215_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_216_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_217_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_218_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_219_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_220_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_221_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_222_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_223_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_224_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_225_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_226_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_227_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_228_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_229_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_230_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_231_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_232_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_233_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_234_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_235_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_236_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_237_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_238_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_239_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_240_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_241_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_242_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_243_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_244_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_245_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_246_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_247_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_248_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_249_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_250_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_251_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_252_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_253_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_254_1.root",
    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_255_1.root")
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_256_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_257_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_258_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_259_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_260_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_261_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_262_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_263_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_264_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_265_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_266_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_267_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_268_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_269_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_270_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_271_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_272_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_273_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_274_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_275_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_276_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_277_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_278_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_279_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_280_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_281_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_282_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_283_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_284_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_285_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_286_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_287_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_288_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_289_1.root",
##    "file:/uscms_data/d2/cheung/slhc/stdgeom/ttbar/ttbar_pu50/valid_reco_290_1.root")

#
# Mark's changes end
#-----------------------------------------------------------------------------------
