#! /usr/bin/env perl
#
# usage: ./runAll -f 1 -l 99 -j 

#===========================================================
$pwd  = $ENV{'PWD'};
$home = $ENV{'HOME'};

$workspace       = "$pwd";

#===========================================================

use Getopt::Std;
getopts('c:f:m12jbl:3');

if ($opt_m) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/MinBias900GeV/MinBias900GeV";
	$res = 553;
}

if ($opt_1) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/Ups1S_7TeV/Ups1STagAndProbe_7TeV";
	$res = 553;
}

if ($opt_2) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/Ups2S_7TeV/Ups2STagAndProbe_7TeV";
	$res = 100553;
}

if ($opt_3) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/Ups3S_7TeV/Ups3STagAndProbe_7TeV";
	$res = 100553;
}


if ($opt_j) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/Jpsi_7TeV/JpsiTagAndProbe_7TeV";
	$res = 443;
}

if ($opt_b) {
	$basefile = "/castor/cern.ch/user/b/bora/NEW_summer09/ppMuMuX_7TeV_JpsiBackground/ppMuMuX_7TeV_JpsiBackground";
	$res = 443;
}

for ($i = $opt_f; $i <= $opt_l; $i++) {
	$file = "$basefile"."_"."$i".".root";
      	print "$basefile   $file\n";
      	system("rfdir $file \>\& rfdir.log"); 
      	$rfdir = `/bin/grep 'No such file or directory' rfdir.log`; 
      	if ( !($rfdir =~ /No such file or directory/) ) {
  	   	@tmp = split(/\//, $file); $lfile = pop(@tmp);
		print  "../bin/runMyReader01 -f $file -b $res \>\& ups_root/$lfile\.log\n";
		system("../bin/runMyReader01 -f $file -b $res \>\& /dev/null");
	 #	system("../bin/runMyReader -f $file -r $res \>\& log/$lfile\.log");
#      	   system("../bin/runMyReader -f $file -o \>\& upsilon1S_root/$file\.log";
       	} else {
			print  "------ $rfdir ---------- \n";
        	} 	
}	
	
