// Class: ReadMLP4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.8.14        [198670]
ROOT Release   : 5.14/00       [331264]
Creator        : delre
Date           : Tue Mar 25 02:47:01 2008
Host           : Linux lxbuild064.cern.ch 2.6.9-55.EL.cernsmp #1 SMP Thu May 10 18:09:56 CEST 2007 i686 i686 i386 GNU/Linux
Dir            : /u1/delre/TMVA/macros
Training events: 30000


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events for var transform]
NbinsMVAPdf: "60" [Number of bins used to create MVA PDF]
NsmoothMVAPdf: "2" [Number of smoothing iterations for MVA PDF]
VerboseLevel: "Info" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs]
TxtWeightFilesOnly: "True" [if True, write all weights as text files]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ntrkiso                       ntrkiso                           'I'    [0,2137]
ptiso                         ptiso                             'F'    [0,57769.6992188]
hcalovecal                    hcalovecal                        'F'    [-0.0187278650701,7.38705682755]
sMajMaj                       sMajMaj                           'F'    [-100,4.54603528976]
sMinMin                       sMinMin                           'F'    [-100,1.47768127918]
ecaliso                       ecaliso                           'F'    [-1.80673420429,3.38462424278]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP4 : public IClassifierReader {

 public:

   // constructor
   ReadMLP4( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP4" ),
        fStatusIsClean( true ),
        fNvars( 6 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ntrkiso", "ptiso", "hcalovecal", "sMajMaj", "sMinMin", "ecaliso" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 2137;
      fVmin[1] = 0;
      fVmax[1] = 57769.69921875;
      fVmin[2] = -0.0187278650701046;
      fVmax[2] = 7.38705682754517;
      fVmin[3] = -100;
      fVmax[3] = 4.5460352897644;
      fVmin[4] = -100;
      fVmax[4] = 1.47768127918243;
      fVmin[5] = -1.8067342042923;
      fVmax[5] = 3.38462424278259;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[7][8];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][7];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP4::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 7; fWeights[2] = new double[7]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0709476279977285;
   fWeightMatrix0to1[1][0] = 16.6848929441711;
   fWeightMatrix0to1[2][0] = 0.916098161218843;
   fWeightMatrix0to1[3][0] = 1.68347453250017;
   fWeightMatrix0to1[4][0] = -2.30764271167774;
   fWeightMatrix0to1[5][0] = 4.46005983586622;
   fWeightMatrix0to1[6][0] = -1.05289336891365;
   fWeightMatrix0to1[0][1] = 2.29842901266875;
   fWeightMatrix0to1[1][1] = -8.40172417915502;
   fWeightMatrix0to1[2][1] = -1.34864065009734;
   fWeightMatrix0to1[3][1] = -1.04591905434952;
   fWeightMatrix0to1[4][1] = 0.335315292840446;
   fWeightMatrix0to1[5][1] = -3.36452394710398;
   fWeightMatrix0to1[6][1] = -0.475283807727018;
   fWeightMatrix0to1[0][2] = -0.183230818813231;
   fWeightMatrix0to1[1][2] = 18.6545297764682;
   fWeightMatrix0to1[2][2] = -0.0229088411729419;
   fWeightMatrix0to1[3][2] = 1.96870892095781;
   fWeightMatrix0to1[4][2] = -0.288269824450615;
   fWeightMatrix0to1[5][2] = 8.99966047508425;
   fWeightMatrix0to1[6][2] = -0.679160903180179;
   fWeightMatrix0to1[0][3] = -1.11407117196381;
   fWeightMatrix0to1[1][3] = 13.1531244239081;
   fWeightMatrix0to1[2][3] = 0.774510428651962;
   fWeightMatrix0to1[3][3] = -1.73363483176029;
   fWeightMatrix0to1[4][3] = -0.89933259789656;
   fWeightMatrix0to1[5][3] = 6.43224470768001;
   fWeightMatrix0to1[6][3] = -1.01366834724451;
   fWeightMatrix0to1[0][4] = -2.29629964213369;
   fWeightMatrix0to1[1][4] = 6.25895859335284;
   fWeightMatrix0to1[2][4] = 1.27358534620233;
   fWeightMatrix0to1[3][4] = 1.08078737814931;
   fWeightMatrix0to1[4][4] = -0.641074863442689;
   fWeightMatrix0to1[5][4] = 2.26013377478423;
   fWeightMatrix0to1[6][4] = 0.322189160005339;
   fWeightMatrix0to1[0][5] = -0.24627141500543;
   fWeightMatrix0to1[1][5] = -0.533671003438492;
   fWeightMatrix0to1[2][5] = 1.47052905361619;
   fWeightMatrix0to1[3][5] = -1.13826728742777;
   fWeightMatrix0to1[4][5] = 1.35825356135903;
   fWeightMatrix0to1[5][5] = 1.35371515310836;
   fWeightMatrix0to1[6][5] = 0.5733794112075;
   fWeightMatrix0to1[0][6] = 1.45985435978917;
   fWeightMatrix0to1[1][6] = 7.77494934188588;
   fWeightMatrix0to1[2][6] = -0.164375097649177;
   fWeightMatrix0to1[3][6] = -2.21500180557504;
   fWeightMatrix0to1[4][6] = 0.443599219241956;
   fWeightMatrix0to1[5][6] = 2.6765833927307;
   fWeightMatrix0to1[6][6] = 1.60122469794287;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.00369073388861;
   fWeightMatrix1to2[1][0] = 0.983169791504901;
   fWeightMatrix1to2[2][0] = 0.796384745096104;
   fWeightMatrix1to2[3][0] = -2.44226026322454;
   fWeightMatrix1to2[4][0] = 1.84391944341218;
   fWeightMatrix1to2[5][0] = -1.29337106723604;
   fWeightMatrix1to2[0][1] = 0.0267688290598618;
   fWeightMatrix1to2[1][1] = -0.976025254715405;
   fWeightMatrix1to2[2][1] = -1.29365745920489;
   fWeightMatrix1to2[3][1] = 0.744851908015788;
   fWeightMatrix1to2[4][1] = 0.640584746351143;
   fWeightMatrix1to2[5][1] = -6.95666245168977;
   fWeightMatrix1to2[0][2] = 0.735711141439426;
   fWeightMatrix1to2[1][2] = 0.193249236311358;
   fWeightMatrix1to2[2][2] = 1.11722752175915;
   fWeightMatrix1to2[3][2] = 2.14467185810229;
   fWeightMatrix1to2[4][2] = -0.785151497924316;
   fWeightMatrix1to2[5][2] = -0.261835617870076;
   fWeightMatrix1to2[0][3] = -1.53109296242079;
   fWeightMatrix1to2[1][3] = 0.306096867931082;
   fWeightMatrix1to2[2][3] = -1.22647963764273;
   fWeightMatrix1to2[3][3] = -1.46313022088623;
   fWeightMatrix1to2[4][3] = -0.948086139094303;
   fWeightMatrix1to2[5][3] = 1.26588510198595;
   fWeightMatrix1to2[0][4] = 1.35505802498435;
   fWeightMatrix1to2[1][4] = 1.86078579019014;
   fWeightMatrix1to2[2][4] = 0.0853772479693059;
   fWeightMatrix1to2[3][4] = -1.16456369620922;
   fWeightMatrix1to2[4][4] = -1.63552951074221;
   fWeightMatrix1to2[5][4] = 1.27269782110144;
   fWeightMatrix1to2[0][5] = 0.791113052941325;
   fWeightMatrix1to2[1][5] = 1.43672001973778;
   fWeightMatrix1to2[2][5] = 0.833400411713991;
   fWeightMatrix1to2[3][5] = 0.795245977550957;
   fWeightMatrix1to2[4][5] = -1.13133390096763;
   fWeightMatrix1to2[5][5] = -2.63451556788524;
   fWeightMatrix1to2[0][6] = 0.0915963633613833;
   fWeightMatrix1to2[1][6] = 1.64334917648243;
   fWeightMatrix1to2[2][6] = -0.719386861128306;
   fWeightMatrix1to2[3][6] = -0.922556777115428;
   fWeightMatrix1to2[4][6] = -1.99612648748452;
   fWeightMatrix1to2[5][6] = -0.342421713843594;
   fWeightMatrix1to2[0][7] = 0.308649647244653;
   fWeightMatrix1to2[1][7] = 2.23141464738001;
   fWeightMatrix1to2[2][7] = -1.23159623720933;
   fWeightMatrix1to2[3][7] = -0.0706869271500693;
   fWeightMatrix1to2[4][7] = 1.34554091056231;
   fWeightMatrix1to2[5][7] = -1.41823118406471;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.824345390014662;
   fWeightMatrix2to3[0][1] = -1.22957924545169;
   fWeightMatrix2to3[0][2] = 0.102769706390788;
   fWeightMatrix2to3[0][3] = -0.453055945541265;
   fWeightMatrix2to3[0][4] = -1.47394012207006;
   fWeightMatrix2to3[0][5] = 0.944014273930884;
   fWeightMatrix2to3[0][6] = 1.04863958345171;
}

inline double ReadMLP4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP4::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP4::Clear() 
{
   // nothing to clear
}
inline double ReadMLP4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
