// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.8.14        [198670]
ROOT Release   : 5.14/00       [331264]
Creator        : delre
Date           : Tue Feb 26 23:46:56 2008
Host           : Linux lxbuild064.cern.ch 2.6.9-55.EL.cernsmp #1 SMP Thu May 10 18:09:56 CEST 2007 i686 i686 i386 GNU/Linux
Dir            : /u1/delre/TMVA/macros
Training events: 20000


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events for var transform]
NbinsMVAPdf: "60" [Number of bins used to create MVA PDF]
NsmoothMVAPdf: "2" [Number of smoothing iterations for MVA PDF]
VerboseLevel: "Info" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs]
TxtWeightFilesOnly: "True" [if True, write all weights as text files]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ntrkiso                       ntrkiso                           'I'    [0,881]
ptiso                         ptiso                             'F'    [0,28062.7832031]
hcalovecal                    hcalovecal                        'F'    [-0.0805005133152,29.2696247101]
sMajMaj                       sMajMaj                           'F'    [0.0401639826596,4.52940559387]
sMinMin                       sMinMin                           'F'    [-1.34399986267,1.5102738142]
ecaliso                       ecaliso                           'F'    [0,23.5740833282]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fStatusIsClean( true ),
        fNvars( 6 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ntrkiso", "ptiso", "hcalovecal", "sMajMaj", "sMinMin", "ecaliso" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 881;
      fVmin[1] = 0;
      fVmax[1] = 28062.783203125;
      fVmin[2] = -0.0805005133152008;
      fVmax[2] = 29.269624710083;
      fVmin[3] = 0.0401639826595783;
      fVmax[3] = 4.52940559387207;
      fVmin[4] = -1.3439998626709;
      fVmax[4] = 1.51027381420135;
      fVmin[5] = 0;
      fVmax[5] = 23.5740833282471;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[7][8];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][7];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 7; fWeights[2] = new double[7]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.938495338730314;
   fWeightMatrix0to1[1][0] = 1.23259195773676;
   fWeightMatrix0to1[2][0] = 5.06409496851243;
   fWeightMatrix0to1[3][0] = 10.7810135403142;
   fWeightMatrix0to1[4][0] = -2.13280054413298;
   fWeightMatrix0to1[5][0] = 14.5122730093784;
   fWeightMatrix0to1[6][0] = -0.693280345044611;
   fWeightMatrix0to1[0][1] = 1.20413926442388;
   fWeightMatrix0to1[1][1] = -1.78518875096458;
   fWeightMatrix0to1[2][1] = -6.462697511068;
   fWeightMatrix0to1[3][1] = -10.022607573253;
   fWeightMatrix0to1[4][1] = -0.755013349232082;
   fWeightMatrix0to1[5][1] = -19.502658686435;
   fWeightMatrix0to1[6][1] = -0.543285188612376;
   fWeightMatrix0to1[0][2] = -0.741997563603379;
   fWeightMatrix0to1[1][2] = 0.27779396911283;
   fWeightMatrix0to1[2][2] = 3.32939948682961;
   fWeightMatrix0to1[3][2] = 9.25146509028517;
   fWeightMatrix0to1[4][2] = -0.0735642836595481;
   fWeightMatrix0to1[5][2] = 17.4625087292424;
   fWeightMatrix0to1[6][2] = -0.404438324241057;
   fWeightMatrix0to1[0][3] = -1.15016283652685;
   fWeightMatrix0to1[1][3] = 0.061235527107765;
   fWeightMatrix0to1[2][3] = 0.975223838975791;
   fWeightMatrix0to1[3][3] = -3.99229309522961;
   fWeightMatrix0to1[4][3] = -0.357748559259846;
   fWeightMatrix0to1[5][3] = 2.59345201569382;
   fWeightMatrix0to1[6][3] = -1.09388137979265;
   fWeightMatrix0to1[0][4] = -1.60224531230513;
   fWeightMatrix0to1[1][4] = 0.237986961826823;
   fWeightMatrix0to1[2][4] = 1.32900177166791;
   fWeightMatrix0to1[3][4] = 2.53997219724896;
   fWeightMatrix0to1[4][4] = -0.27129819827587;
   fWeightMatrix0to1[5][4] = -0.216652356217403;
   fWeightMatrix0to1[6][4] = 0.257479831152782;
   fWeightMatrix0to1[0][5] = -0.58866333417884;
   fWeightMatrix0to1[1][5] = -1.8366933148344;
   fWeightMatrix0to1[2][5] = 3.13668446005105;
   fWeightMatrix0to1[3][5] = 0.706718818991362;
   fWeightMatrix0to1[4][5] = 0.856884000908914;
   fWeightMatrix0to1[5][5] = 4.60377080884629;
   fWeightMatrix0to1[6][5] = 0.772618033308933;
   fWeightMatrix0to1[0][6] = 2.6690082005585;
   fWeightMatrix0to1[1][6] = 1.96792793487765;
   fWeightMatrix0to1[2][6] = 4.95901352689667;
   fWeightMatrix0to1[3][6] = 7.64464958587885;
   fWeightMatrix0to1[4][6] = 1.05269051757594;
   fWeightMatrix0to1[5][6] = 18.8043372836936;
   fWeightMatrix0to1[6][6] = 1.61032383181467;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.5224440119932;
   fWeightMatrix1to2[1][0] = 0.596672423441608;
   fWeightMatrix1to2[2][0] = 1.39190669636774;
   fWeightMatrix1to2[3][0] = -1.91911593047274;
   fWeightMatrix1to2[4][0] = 2.16409281878431;
   fWeightMatrix1to2[5][0] = -1.4160346742217;
   fWeightMatrix1to2[0][1] = -0.656841760243153;
   fWeightMatrix1to2[1][1] = -2.12107514083728;
   fWeightMatrix1to2[2][1] = -1.66554687999581;
   fWeightMatrix1to2[3][1] = 1.32211638485813;
   fWeightMatrix1to2[4][1] = 1.63283463374614;
   fWeightMatrix1to2[5][1] = -1.08775708311546;
   fWeightMatrix1to2[0][2] = 0.121350152653095;
   fWeightMatrix1to2[1][2] = 2.94625530920562;
   fWeightMatrix1to2[2][2] = 0.633744285798651;
   fWeightMatrix1to2[3][2] = 1.68446262320916;
   fWeightMatrix1to2[4][2] = -0.410759740187764;
   fWeightMatrix1to2[5][2] = -0.0965582285031295;
   fWeightMatrix1to2[0][3] = -1.5032319570667;
   fWeightMatrix1to2[1][3] = 5.07529579483559;
   fWeightMatrix1to2[2][3] = -0.752822399451836;
   fWeightMatrix1to2[3][3] = -0.744821926688538;
   fWeightMatrix1to2[4][3] = -0.960602785920065;
   fWeightMatrix1to2[5][3] = 1.31684376080479;
   fWeightMatrix1to2[0][4] = 1.74565547830319;
   fWeightMatrix1to2[1][4] = 0.210616372698903;
   fWeightMatrix1to2[2][4] = -0.273774406374218;
   fWeightMatrix1to2[3][4] = -1.69600602421713;
   fWeightMatrix1to2[4][4] = -0.936155899174215;
   fWeightMatrix1to2[5][4] = 1.39760184293223;
   fWeightMatrix1to2[0][5] = 0.650167879036846;
   fWeightMatrix1to2[1][5] = 7.39736746538432;
   fWeightMatrix1to2[2][5] = 0.688408531862124;
   fWeightMatrix1to2[3][5] = 0.864530768999408;
   fWeightMatrix1to2[4][5] = 0.0184852296216373;
   fWeightMatrix1to2[5][5] = -0.868251288165122;
   fWeightMatrix1to2[0][6] = 0.0534673607768364;
   fWeightMatrix1to2[1][6] = 0.159010551116695;
   fWeightMatrix1to2[2][6] = -1.0361489623409;
   fWeightMatrix1to2[3][6] = -1.68671981730566;
   fWeightMatrix1to2[4][6] = -0.737470062468204;
   fWeightMatrix1to2[5][6] = 0.17076329799642;
   fWeightMatrix1to2[0][7] = 0.130181790850096;
   fWeightMatrix1to2[1][7] = 0.723268140694634;
   fWeightMatrix1to2[2][7] = -1.539433075671;
   fWeightMatrix1to2[3][7] = -0.958034526699977;
   fWeightMatrix1to2[4][7] = 2.59252747662449;
   fWeightMatrix1to2[5][7] = -0.47919722969987;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.704464394747389;
   fWeightMatrix2to3[0][1] = -0.939121656257991;
   fWeightMatrix2to3[0][2] = 0.418736392685287;
   fWeightMatrix2to3[0][3] = -1.15034312159733;
   fWeightMatrix2to3[0][4] = -1.31656481962632;
   fWeightMatrix2to3[0][5] = -0.0089775271966945;
   fWeightMatrix2to3[0][6] = 1.22889598390603;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
