// Class: ReadMLP1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.8.14        [198670]
ROOT Release   : 5.14/00       [331264]
Creator        : delre
Date           : Tue Mar 25 08:55:42 2008
Host           : Linux lxbuild064.cern.ch 2.6.9-55.EL.cernsmp #1 SMP Thu May 10 18:09:56 CEST 2007 i686 i686 i386 GNU/Linux
Dir            : /u1/delre/TMVA/macros
Training events: 10000


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events for var transform]
NbinsMVAPdf: "60" [Number of bins used to create MVA PDF]
NsmoothMVAPdf: "2" [Number of smoothing iterations for MVA PDF]
VerboseLevel: "Info" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs]
TxtWeightFilesOnly: "True" [if True, write all weights as text files]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ntrkiso                       ntrkiso                           'I'    [0,694]
ptiso                         ptiso                             'F'    [0,160925.328125]
hcalovecal                    hcalovecal                        'F'    [-0.135096207261,26.7717552185]
sMajMaj                       sMajMaj                           'F'    [-100,3.54368567467]
sMinMin                       sMinMin                           'F'    [-100,1.61012434959]
ecaliso                       ecaliso                           'F'    [-1.79862463474,14.7481126785]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1" ),
        fStatusIsClean( true ),
        fNvars( 6 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ntrkiso", "ptiso", "hcalovecal", "sMajMaj", "sMinMin", "ecaliso" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 694;
      fVmin[1] = 0;
      fVmax[1] = 160925.328125;
      fVmin[2] = -0.135096207261086;
      fVmax[2] = 26.7717552185059;
      fVmin[3] = -100;
      fVmax[3] = 3.54368567466736;
      fVmin[4] = -100;
      fVmax[4] = 1.61012434959412;
      fVmin[5] = -1.79862463474274;
      fVmax[5] = 14.7481126785278;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[7][8];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][7];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 7; fWeights[2] = new double[7]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0140579921956905;
   fWeightMatrix0to1[1][0] = 12.9940934449279;
   fWeightMatrix0to1[2][0] = 9.72958767274799;
   fWeightMatrix0to1[3][0] = 2.04529865418545;
   fWeightMatrix0to1[4][0] = -4.68779870651854;
   fWeightMatrix0to1[5][0] = 4.03638155008675;
   fWeightMatrix0to1[6][0] = -2.13669559777731;
   fWeightMatrix0to1[0][1] = 2.32373230296212;
   fWeightMatrix0to1[1][1] = -4.15002651790371;
   fWeightMatrix0to1[2][1] = -6.19190829984932;
   fWeightMatrix0to1[3][1] = -1.25830860927406;
   fWeightMatrix0to1[4][1] = -0.00420184718137086;
   fWeightMatrix0to1[5][1] = -4.28334806591141;
   fWeightMatrix0to1[6][1] = 0.191466979637516;
   fWeightMatrix0to1[0][2] = -0.317515578251545;
   fWeightMatrix0to1[1][2] = 7.03546207037874;
   fWeightMatrix0to1[2][2] = 8.59128193249477;
   fWeightMatrix0to1[3][2] = 1.98044339327411;
   fWeightMatrix0to1[4][2] = -1.26773379646074;
   fWeightMatrix0to1[5][2] = 7.20052777968316;
   fWeightMatrix0to1[6][2] = -1.40176369339227;
   fWeightMatrix0to1[0][3] = -0.894271362065809;
   fWeightMatrix0to1[1][3] = 6.31937354416958;
   fWeightMatrix0to1[2][3] = 7.96410779253019;
   fWeightMatrix0to1[3][3] = -1.56719049099053;
   fWeightMatrix0to1[4][3] = -1.96167127481225;
   fWeightMatrix0to1[5][3] = 6.32288560012236;
   fWeightMatrix0to1[6][3] = -2.30598405217491;
   fWeightMatrix0to1[0][4] = -2.06133940319653;
   fWeightMatrix0to1[1][4] = 4.51283911959791;
   fWeightMatrix0to1[2][4] = 7.1256145686171;
   fWeightMatrix0to1[3][4] = 1.26776613811406;
   fWeightMatrix0to1[4][4] = -1.77601814901591;
   fWeightMatrix0to1[5][4] = 3.71088822898932;
   fWeightMatrix0to1[6][4] = -0.675577211872672;
   fWeightMatrix0to1[0][5] = -0.0391900396538885;
   fWeightMatrix0to1[1][5] = -1.43895017344412;
   fWeightMatrix0to1[2][5] = 9.42420329531232;
   fWeightMatrix0to1[3][5] = -0.982734655147728;
   fWeightMatrix0to1[4][5] = 2.4821817159419;
   fWeightMatrix0to1[5][5] = 8.51757496430469;
   fWeightMatrix0to1[6][5] = 0.268542115872128;
   fWeightMatrix0to1[0][6] = 1.6879363666926;
   fWeightMatrix0to1[1][6] = 3.99666864647977;
   fWeightMatrix0to1[2][6] = 4.40704092100273;
   fWeightMatrix0to1[3][6] = -2.00115648361483;
   fWeightMatrix0to1[4][6] = -0.184133852618853;
   fWeightMatrix0to1[5][6] = 3.10906677603925;
   fWeightMatrix0to1[6][6] = 0.835109507553649;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.130890066571635;
   fWeightMatrix1to2[1][0] = 0.948744606063642;
   fWeightMatrix1to2[2][0] = 1.14716281586808;
   fWeightMatrix1to2[3][0] = -2.05910680409804;
   fWeightMatrix1to2[4][0] = 2.53323024654528;
   fWeightMatrix1to2[5][0] = -0.537471210931641;
   fWeightMatrix1to2[0][1] = 0.642473269906576;
   fWeightMatrix1to2[1][1] = -0.989204712590617;
   fWeightMatrix1to2[2][1] = -1.56586069205576;
   fWeightMatrix1to2[3][1] = 2.02259186398993;
   fWeightMatrix1to2[4][1] = 2.9254494567027;
   fWeightMatrix1to2[5][1] = -5.42486052799952;
   fWeightMatrix1to2[0][2] = 5.47812643202116;
   fWeightMatrix1to2[1][2] = -1.53752847661941;
   fWeightMatrix1to2[2][2] = 0.994891628062827;
   fWeightMatrix1to2[3][2] = 0.886687556963464;
   fWeightMatrix1to2[4][2] = -0.942982899742454;
   fWeightMatrix1to2[5][2] = -2.54597574542855;
   fWeightMatrix1to2[0][3] = -2.43385648659137;
   fWeightMatrix1to2[1][3] = 0.169328902732835;
   fWeightMatrix1to2[2][3] = -0.455531330036354;
   fWeightMatrix1to2[3][3] = -1.07002879509246;
   fWeightMatrix1to2[4][3] = -0.586313203986099;
   fWeightMatrix1to2[5][3] = 2.09895422141264;
   fWeightMatrix1to2[0][4] = 0.392362410925562;
   fWeightMatrix1to2[1][4] = 0.762320234966835;
   fWeightMatrix1to2[2][4] = -0.035843550038831;
   fWeightMatrix1to2[3][4] = -1.71462354093419;
   fWeightMatrix1to2[4][4] = -0.623999185722527;
   fWeightMatrix1to2[5][4] = 2.21203984098503;
   fWeightMatrix1to2[0][5] = 3.67515522836967;
   fWeightMatrix1to2[1][5] = 1.86670417659008;
   fWeightMatrix1to2[2][5] = 0.940317166166083;
   fWeightMatrix1to2[3][5] = 0.754847398355278;
   fWeightMatrix1to2[4][5] = -1.37369065672155;
   fWeightMatrix1to2[5][5] = -2.28869221669252;
   fWeightMatrix1to2[0][6] = -0.779576965256122;
   fWeightMatrix1to2[1][6] = 1.77022388471987;
   fWeightMatrix1to2[2][6] = -0.976803614182701;
   fWeightMatrix1to2[3][6] = -1.09774090608496;
   fWeightMatrix1to2[4][6] = -1.72992407757298;
   fWeightMatrix1to2[5][6] = 0.488527343620499;
   fWeightMatrix1to2[0][7] = 1.17567789373607;
   fWeightMatrix1to2[1][7] = 2.34974255796625;
   fWeightMatrix1to2[2][7] = -2.02093601198474;
   fWeightMatrix1to2[3][7] = -0.430943894056912;
   fWeightMatrix1to2[4][7] = 0.834447909265354;
   fWeightMatrix1to2[5][7] = -2.2402547692135;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.301913588546492;
   fWeightMatrix2to3[0][1] = -0.365926093691137;
   fWeightMatrix2to3[0][2] = 0.674046080288437;
   fWeightMatrix2to3[0][3] = 0.288022924796078;
   fWeightMatrix2to3[0][4] = -0.382914064267821;
   fWeightMatrix2to3[0][5] = 0.924311613643769;
   fWeightMatrix2to3[0][6] = 0.579953152222384;
}

inline double ReadMLP1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
