// Class: ReadMLP3
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.8.14        [198670]
ROOT Release   : 5.14/00       [331264]
Creator        : delre
Date           : Tue Mar 25 02:41:09 2008
Host           : Linux lxbuild064.cern.ch 2.6.9-55.EL.cernsmp #1 SMP Thu May 10 18:09:56 CEST 2007 i686 i686 i386 GNU/Linux
Dir            : /u1/delre/TMVA/macros
Training events: 40000


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events for var transform]
NbinsMVAPdf: "60" [Number of bins used to create MVA PDF]
NsmoothMVAPdf: "2" [Number of smoothing iterations for MVA PDF]
VerboseLevel: "Info" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs]
TxtWeightFilesOnly: "True" [if True, write all weights as text files]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ntrkiso                       ntrkiso                           'I'    [0,1860]
ptiso                         ptiso                             'F'    [0,44474.7929688]
hcalovecal                    hcalovecal                        'F'    [-0.0466493405402,10.9895515442]
sMajMaj                       sMajMaj                           'F'    [-100,4.40880966187]
sMinMin                       sMinMin                           'F'    [-100,1.8807694912]
ecaliso                       ecaliso                           'F'    [-1.80635762215,15.4047851562]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP3 : public IClassifierReader {

 public:

   // constructor
   ReadMLP3( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP3" ),
        fStatusIsClean( true ),
        fNvars( 6 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ntrkiso", "ptiso", "hcalovecal", "sMajMaj", "sMinMin", "ecaliso" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 1860;
      fVmin[1] = 0;
      fVmax[1] = 44474.79296875;
      fVmin[2] = -0.0466493405401707;
      fVmax[2] = 10.9895515441895;
      fVmin[3] = -100;
      fVmax[3] = 4.40880966186523;
      fVmin[4] = -100;
      fVmax[4] = 1.88076949119568;
      fVmin[5] = -1.80635762214661;
      fVmax[5] = 15.40478515625;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP3() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[7][8];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][7];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP3::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 7; fWeights[2] = new double[7]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0394301425680555;
   fWeightMatrix0to1[1][0] = 14.3738997456271;
   fWeightMatrix0to1[2][0] = 2.74124721134935;
   fWeightMatrix0to1[3][0] = 2.03622361987681;
   fWeightMatrix0to1[4][0] = -5.4395518921411;
   fWeightMatrix0to1[5][0] = 10.4137877470907;
   fWeightMatrix0to1[6][0] = -3.03232660262176;
   fWeightMatrix0to1[0][1] = 2.28004535448279;
   fWeightMatrix0to1[1][1] = -4.79374370872709;
   fWeightMatrix0to1[2][1] = -2.03648248575947;
   fWeightMatrix0to1[3][1] = -1.26019426298625;
   fWeightMatrix0to1[4][1] = 0.817690886878363;
   fWeightMatrix0to1[5][1] = -5.79688916365494;
   fWeightMatrix0to1[6][1] = 0.737563293955922;
   fWeightMatrix0to1[0][2] = -0.289563521051303;
   fWeightMatrix0to1[1][2] = 17.1887749183998;
   fWeightMatrix0to1[2][2] = 2.74023980528077;
   fWeightMatrix0to1[3][2] = 1.99999377130355;
   fWeightMatrix0to1[4][2] = -4.36220776091984;
   fWeightMatrix0to1[5][2] = 18.6876010420388;
   fWeightMatrix0to1[6][2] = -3.59867381920786;
   fWeightMatrix0to1[0][3] = -0.953659592832896;
   fWeightMatrix0to1[1][3] = 10.938619229077;
   fWeightMatrix0to1[2][3] = 2.14986832862458;
   fWeightMatrix0to1[3][3] = -1.53215658663364;
   fWeightMatrix0to1[4][3] = -3.86918531046706;
   fWeightMatrix0to1[5][3] = 12.1809630168973;
   fWeightMatrix0to1[6][3] = -4.11043028359011;
   fWeightMatrix0to1[0][4] = -2.12002572579293;
   fWeightMatrix0to1[1][4] = 8.25250051402706;
   fWeightMatrix0to1[2][4] = 2.37846557021912;
   fWeightMatrix0to1[3][4] = 1.29819022475829;
   fWeightMatrix0to1[4][4] = -3.41922901196869;
   fWeightMatrix0to1[5][4] = 7.96234497504746;
   fWeightMatrix0to1[6][4] = -2.33333262386396;
   fWeightMatrix0to1[0][5] = -0.0803281868653793;
   fWeightMatrix0to1[1][5] = -1.94840643423493;
   fWeightMatrix0to1[2][5] = 1.95741339392536;
   fWeightMatrix0to1[3][5] = -0.938125603550311;
   fWeightMatrix0to1[4][5] = 0.697316543145075;
   fWeightMatrix0to1[5][5] = 2.02778039295034;
   fWeightMatrix0to1[6][5] = -0.181623566754635;
   fWeightMatrix0to1[0][6] = 1.65167506881649;
   fWeightMatrix0to1[1][6] = 6.3259763686176;
   fWeightMatrix0to1[2][6] = 0.405874151023362;
   fWeightMatrix0to1[3][6] = -2.0007846265683;
   fWeightMatrix0to1[4][6] = -1.38745427585613;
   fWeightMatrix0to1[5][6] = 5.3146702708023;
   fWeightMatrix0to1[6][6] = -0.398039262849845;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.47427641305303;
   fWeightMatrix1to2[1][0] = 1.2420963062019;
   fWeightMatrix1to2[2][0] = 0.596221139797057;
   fWeightMatrix1to2[3][0] = -2.61585436520051;
   fWeightMatrix1to2[4][0] = 1.98174742853693;
   fWeightMatrix1to2[5][0] = -1.32498020163324;
   fWeightMatrix1to2[0][1] = -1.01772126452011;
   fWeightMatrix1to2[1][1] = -1.50179082390181;
   fWeightMatrix1to2[2][1] = -1.69793265813248;
   fWeightMatrix1to2[3][1] = 1.04336734537193;
   fWeightMatrix1to2[4][1] = 4.94163193063505;
   fWeightMatrix1to2[5][1] = -4.42034933312963;
   fWeightMatrix1to2[0][2] = 0.933825949853501;
   fWeightMatrix1to2[1][2] = -0.461508705922661;
   fWeightMatrix1to2[2][2] = 0.325200880682722;
   fWeightMatrix1to2[3][2] = 1.47848566826155;
   fWeightMatrix1to2[4][2] = 1.14066833901406;
   fWeightMatrix1to2[5][2] = -0.71199822219283;
   fWeightMatrix1to2[0][3] = -1.08933334318554;
   fWeightMatrix1to2[1][3] = 0.567772810086383;
   fWeightMatrix1to2[2][3] = -1.20181034738189;
   fWeightMatrix1to2[3][3] = -1.65483664204201;
   fWeightMatrix1to2[4][3] = -1.6718026405297;
   fWeightMatrix1to2[5][3] = 1.19025946592658;
   fWeightMatrix1to2[0][4] = 0.623630183261862;
   fWeightMatrix1to2[1][4] = 2.02011177659849;
   fWeightMatrix1to2[2][4] = -0.0655185738064126;
   fWeightMatrix1to2[3][4] = -0.976193394366196;
   fWeightMatrix1to2[4][4] = -1.70961387949072;
   fWeightMatrix1to2[5][4] = 1.29858089935552;
   fWeightMatrix1to2[0][5] = 0.793404091250044;
   fWeightMatrix1to2[1][5] = 0.139863378517272;
   fWeightMatrix1to2[2][5] = 0.840853147273749;
   fWeightMatrix1to2[3][5] = 0.80457936435296;
   fWeightMatrix1to2[4][5] = 4.20584344319424;
   fWeightMatrix1to2[5][5] = -3.38639266177938;
   fWeightMatrix1to2[0][6] = -0.968983434229337;
   fWeightMatrix1to2[1][6] = 2.33736435568475;
   fWeightMatrix1to2[2][6] = -0.870111387676728;
   fWeightMatrix1to2[3][6] = -0.873246156023534;
   fWeightMatrix1to2[4][6] = -1.39315127280298;
   fWeightMatrix1to2[5][6] = 0.536719018134811;
   fWeightMatrix1to2[0][7] = -0.174095841149176;
   fWeightMatrix1to2[1][7] = 1.88207846052098;
   fWeightMatrix1to2[2][7] = -1.26896716848766;
   fWeightMatrix1to2[3][7] = 0.128239983729633;
   fWeightMatrix1to2[4][7] = 2.00569805121396;
   fWeightMatrix1to2[5][7] = -1.36871544078934;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.0245790455160113;
   fWeightMatrix2to3[0][1] = -0.060906143020061;
   fWeightMatrix2to3[0][2] = 0.0636557356815916;
   fWeightMatrix2to3[0][3] = 0.971419334585056;
   fWeightMatrix2to3[0][4] = -0.772444238397793;
   fWeightMatrix2to3[0][5] = 0.229682242613173;
   fWeightMatrix2to3[0][6] = -0.974638844635182;
}

inline double ReadMLP3::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP3::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP3::Clear() 
{
   // nothing to clear
}
inline double ReadMLP3::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
