// Class: ReadMLP2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.8.14        [198670]
ROOT Release   : 5.14/00       [331264]
Creator        : delre
Date           : Tue Mar 25 08:59:15 2008
Host           : Linux lxbuild064.cern.ch 2.6.9-55.EL.cernsmp #1 SMP Thu May 10 18:09:56 CEST 2007 i686 i686 i386 GNU/Linux
Dir            : /u1/delre/TMVA/macros
Training events: 20000


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events for var transform]
NbinsMVAPdf: "60" [Number of bins used to create MVA PDF]
NsmoothMVAPdf: "2" [Number of smoothing iterations for MVA PDF]
VerboseLevel: "Info" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs]
TxtWeightFilesOnly: "True" [if True, write all weights as text files]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
ntrkiso                       ntrkiso                           'I'    [0,928]
ptiso                         ptiso                             'F'    [0,30823.8808594]
hcalovecal                    hcalovecal                        'F'    [-0.0979818329215,20.0135593414]
sMajMaj                       sMajMaj                           'F'    [-100,4.67778539658]
sMinMin                       sMinMin                           'F'    [-100,1.84776878357]
ecaliso                       ecaliso                           'F'    [-1.80753231049,17.6181793213]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP2 : public IClassifierReader {

 public:

   // constructor
   ReadMLP2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP2" ),
        fStatusIsClean( true ),
        fNvars( 6 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ntrkiso", "ptiso", "hcalovecal", "sMajMaj", "sMinMin", "ecaliso" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 928;
      fVmin[1] = 0;
      fVmax[1] = 30823.880859375;
      fVmin[2] = -0.097981832921505;
      fVmax[2] = 20.0135593414307;
      fVmin[3] = -100;
      fVmax[3] = 4.67778539657593;
      fVmin[4] = -100;
      fVmax[4] = 1.84776878356934;
      fVmin[5] = -1.80753231048584;
      fVmax[5] = 17.6181793212891;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[7][8];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][7];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP2::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 7; fWeights[2] = new double[7]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0907756342054851;
   fWeightMatrix0to1[1][0] = 14.6559425804677;
   fWeightMatrix0to1[2][0] = 7.81582106530827;
   fWeightMatrix0to1[3][0] = 2.05063757182385;
   fWeightMatrix0to1[4][0] = -10.1774311003023;
   fWeightMatrix0to1[5][0] = 6.10147593185061;
   fWeightMatrix0to1[6][0] = -5.39207872002667;
   fWeightMatrix0to1[0][1] = 2.23820798357367;
   fWeightMatrix0to1[1][1] = -5.05676686331101;
   fWeightMatrix0to1[2][1] = -4.71519573452297;
   fWeightMatrix0to1[3][1] = -1.22467169152056;
   fWeightMatrix0to1[4][1] = 1.76551389887728;
   fWeightMatrix0to1[5][1] = -4.73437393932952;
   fWeightMatrix0to1[6][1] = 1.10071163517866;
   fWeightMatrix0to1[0][2] = -0.413012247902777;
   fWeightMatrix0to1[1][2] = 12.6095789223341;
   fWeightMatrix0to1[2][2] = 7.43215415717304;
   fWeightMatrix0to1[3][2] = 2.03325839060988;
   fWeightMatrix0to1[4][2] = -6.94731700509721;
   fWeightMatrix0to1[5][2] = 9.20859870633645;
   fWeightMatrix0to1[6][2] = -4.4022100326046;
   fWeightMatrix0to1[0][3] = -0.857875306376916;
   fWeightMatrix0to1[1][3] = 8.55424900727197;
   fWeightMatrix0to1[2][3] = 6.21504895672178;
   fWeightMatrix0to1[3][3] = -1.56667849078282;
   fWeightMatrix0to1[4][3] = -5.29168257726496;
   fWeightMatrix0to1[5][3] = 7.62934918476706;
   fWeightMatrix0to1[6][3] = -4.30607315408227;
   fWeightMatrix0to1[0][4] = -2.02147920782775;
   fWeightMatrix0to1[1][4] = 7.17882080113368;
   fWeightMatrix0to1[2][4] = 6.01454857861106;
   fWeightMatrix0to1[3][4] = 1.26001034725303;
   fWeightMatrix0to1[4][4] = -5.0089705025989;
   fWeightMatrix0to1[5][4] = 5.02269340040074;
   fWeightMatrix0to1[6][4] = -2.70021660096015;
   fWeightMatrix0to1[0][5] = -0.124070440206921;
   fWeightMatrix0to1[1][5] = -0.938445632979131;
   fWeightMatrix0to1[2][5] = 5.78211445665995;
   fWeightMatrix0to1[3][5] = -0.913944075042408;
   fWeightMatrix0to1[4][5] = 3.09794240011994;
   fWeightMatrix0to1[5][5] = 7.34048253479679;
   fWeightMatrix0to1[6][5] = 1.3553233937854;
   fWeightMatrix0to1[0][6] = 1.75453963655911;
   fWeightMatrix0to1[1][6] = 6.05635102366682;
   fWeightMatrix0to1[2][6] = 3.29558760201539;
   fWeightMatrix0to1[3][6] = -2.03601830872624;
   fWeightMatrix0to1[4][6] = -2.52500353973276;
   fWeightMatrix0to1[5][6] = 3.93248313156614;
   fWeightMatrix0to1[6][6] = -0.635427750675357;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.62013138041738;
   fWeightMatrix1to2[1][0] = 1.21654574286353;
   fWeightMatrix1to2[2][0] = 1.2925495982402;
   fWeightMatrix1to2[3][0] = -2.70654085731363;
   fWeightMatrix1to2[4][0] = 2.99434410814166;
   fWeightMatrix1to2[5][0] = -0.743414470997647;
   fWeightMatrix1to2[0][1] = -2.00896243138312;
   fWeightMatrix1to2[1][1] = -1.58587170226536;
   fWeightMatrix1to2[2][1] = -1.73096339694267;
   fWeightMatrix1to2[3][1] = 4.77244306465893;
   fWeightMatrix1to2[4][1] = 2.18486440762286;
   fWeightMatrix1to2[5][1] = -2.99621397980294;
   fWeightMatrix1to2[0][2] = 1.19698868311088;
   fWeightMatrix1to2[1][2] = -1.29828553909806;
   fWeightMatrix1to2[2][2] = 0.686601318176068;
   fWeightMatrix1to2[3][2] = 2.84527329446107;
   fWeightMatrix1to2[4][2] = 0.649572497851956;
   fWeightMatrix1to2[5][2] = -2.23517699859562;
   fWeightMatrix1to2[0][3] = -0.943045603916821;
   fWeightMatrix1to2[1][3] = 0.40829083522904;
   fWeightMatrix1to2[2][3] = -0.106408898289894;
   fWeightMatrix1to2[3][3] = -1.68367531879192;
   fWeightMatrix1to2[4][3] = -1.15723252968754;
   fWeightMatrix1to2[5][3] = 1.75666969344478;
   fWeightMatrix1to2[0][4] = 1.75198313211288;
   fWeightMatrix1to2[1][4] = 1.4029225968964;
   fWeightMatrix1to2[2][4] = -0.29422389185714;
   fWeightMatrix1to2[3][4] = -3.67116904500687;
   fWeightMatrix1to2[4][4] = -1.26291020793795;
   fWeightMatrix1to2[5][4] = 1.53547973656388;
   fWeightMatrix1to2[0][5] = 1.13326876641922;
   fWeightMatrix1to2[1][5] = 0.806983028826467;
   fWeightMatrix1to2[2][5] = 0.667478241656563;
   fWeightMatrix1to2[3][5] = 2.85495200091266;
   fWeightMatrix1to2[4][5] = -0.766730051937977;
   fWeightMatrix1to2[5][5] = -3.54312366141431;
   fWeightMatrix1to2[0][6] = 0.452044260550693;
   fWeightMatrix1to2[1][6] = 1.7384300382348;
   fWeightMatrix1to2[2][6] = -0.994873417937963;
   fWeightMatrix1to2[3][6] = -1.825595248289;
   fWeightMatrix1to2[4][6] = -0.984181300659497;
   fWeightMatrix1to2[5][6] = 0.0439977981916153;
   fWeightMatrix1to2[0][7] = -0.330554474214433;
   fWeightMatrix1to2[1][7] = 2.0106024848529;
   fWeightMatrix1to2[2][7] = -2.37354929233329;
   fWeightMatrix1to2[3][7] = 0.193192541822084;
   fWeightMatrix1to2[4][7] = 1.41304739800863;
   fWeightMatrix1to2[5][7] = -1.90709727964595;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.166641369485147;
   fWeightMatrix2to3[0][1] = -0.717063478539558;
   fWeightMatrix2to3[0][2] = 0.623603690515696;
   fWeightMatrix2to3[0][3] = -0.842001679662349;
   fWeightMatrix2to3[0][4] = -0.854568139869437;
   fWeightMatrix2to3[0][5] = 0.115224538882429;
   fWeightMatrix2to3[0][6] = 0.542802891874882;
}

inline double ReadMLP2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP2::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP2::Clear() 
{
   // nothing to clear
}
inline double ReadMLP2::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
