read :     read.cpp 
	c++ `root-config --cflags --libs` -m32 -o read read.cpp

min  :     minimize.cpp GenericMinL3Algorithm.cc
	c++ `root-config --cflags --libs` -m32 -o min minimize.cpp GenericMinL3Algorithm.cc

