include $(XDAQ_ROOT)/config/mfAutoconf.rules
include $(XDAQ_ROOT)/config/mfDefs.$(XDAQ_OS)

Project=RecoLuminosity/HLXReadOut

Packages= \
	CoreUtils \
	HLXCoreLibs \
	StandAlone

include $(XDAQ_ROOT)/config/Makefile.rules
