import FWCore.ParameterSet.Config as cms

from EgammaAnalysis.EgammaIsolationProducers.egammaSuperClusterMerger_cfi import *
from EgammaAnalysis.EgammaIsolationProducers.egammaBasicClusterMerger_cfi import *
from EgammaAnalysis.EgammaIsolationProducers.egammaEcalIsolation_cfi import *
egammaEcalIsolationSequence = cms.Sequence(egammaSuperClusterMerger*egammaBasicClusterMerger*egammaEcalIsolation)

