import FWCore.ParameterSet.Config as cms

promptanatrigger = cms.EDProducer("PromptAna_Trigger",
                                  InputTag = cms.InputTag('gtDigis'),
                                  NBxOutput = cms.int32(1), #support for either 1 or 3
                                  TRGTag = cms.InputTag("TriggerResults","","HLT"), 
                                  # This list is intended to be exhaustive,
                                  # i.e. all L1 trigger names that were available when the events were taken,
                                  # not only those relevant for some analysis or other.
                                  # You will be warned in endJob() if this list is insufficient.
                                  # Do not prune the list unless you understand what you are doing.
                                  # If endJob() instructs you to add to the list, then please do so.
                                  
                                  StoreByName = cms.bool(False),
                                  
                                ListOfTriggerNames = cms.vstring(
				"L1_DoubleEG05_TopBottom",
				"L1_DoubleEG1",
				"L1_DoubleEG5",
				"L1_DoubleHfBitCountsRing1_P1N1",
				"L1_DoubleHfBitCountsRing2_P1N1",
				"L1_DoubleHfRingEtSumsRing1_P200N200",
				"L1_DoubleHfRingEtSumsRing1_P4N4",
				"L1_DoubleHfRingEtSumsRing2_P200N200",
				"L1_DoubleHfRingEtSumsRing2_P4N4",
				"L1_DoubleJet30",
				"L1_DoubleMu3",
				"L1_DoubleMuOpen",
				"L1_DoubleMuTopBottom",
				"L1_DoubleTauJet14",
				"L1_ETM20",
				"L1_ETM30",
				"L1_ETM80",
				"L1_ETT60",
				"L1_HTT100",
				"L1_HTT200",
				"L1_IsoEG10_Jet6_ForJet6",
				"L1_MinBias_HTT10",
				"L1_Mu3QE8_Jet6",
				"L1_Mu5QE8_Jet6",
				"L1_QuadJet6",
				"L1_SingleEG1",
				"L1_SingleEG10",
				"L1_SingleEG12",
				"L1_SingleEG15",
				"L1_SingleEG2",
				"L1_SingleEG20",
				"L1_SingleEG5",
				"L1_SingleEG8",
				"L1_SingleHfBitCountsRing1_1",
				"L1_SingleHfBitCountsRing2_1",
				"L1_SingleHfRingEtSumsRing1_200",
				"L1_SingleHfRingEtSumsRing1_4",
				"L1_SingleHfRingEtSumsRing2_200",
				"L1_SingleHfRingEtSumsRing2_4",
				"L1_SingleIsoEG10",
				"L1_SingleIsoEG12",
				"L1_SingleIsoEG15",
				"L1_SingleIsoEG5",
				"L1_SingleIsoEG8",
				"L1_SingleJet10",
				"L1_SingleJet10_NotBptxC",
				"L1_SingleJet20",
				"L1_SingleJet30",
				"L1_SingleJet40",
				"L1_SingleJet50",
                                "L1_SingleJet6",
                                "L1_SingleJet60",
                                "L1_SingleMu0",
                                "L1_SingleMu10",
                                "L1_SingleMu14",
                                "L1_SingleMu20",
                                "L1_SingleMu3",
                                "L1_SingleMu5",
                                "L1_SingleMu7",
                                "L1_SingleMuBeamHalo",
                                "L1_SingleMuOpen",
                                "L1_SingleTauJet10",
                                "L1_SingleTauJet20",
                                "L1_SingleTauJet30",
                                "L1_SingleTauJet50",
                                "L1_TripleJet14",
                                "L1_ZeroBias",
                                )
                                          )
