{
  gROOT->Reset();
  gStyle->SetPalette(1);
  gStyle                  -> SetOptStat(1111);
  


  TCanvas c2h("c2h","2-d options",10,10,800,600);
  c2h.SetFillColor(10);
  gPad->SetDrawOption("e1p");
  TFile f("coefficients_1mln.root");  
 	   h1mlnetacoefpl1_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl1_noise.gif");
	   h1mlnetacoefpl2_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl2_noise.gif");
	   h1mlnetacoefpl3_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl3_noise.gif");
	   h1mlnetacoefpl4_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl4_noise.gif");
	   h1mlnetacoefpl5_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl5_noise.gif");
	   h1mlnetacoefpl6_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl6_noise.gif");
	   h1mlnetacoefpl7_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl7_noise.gif");
	   h1mlnetacoefpl8_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl8_noise.gif");
	   h1mlnetacoefpl9_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl9_noise.gif");
	   h1mlnetacoefpl10_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl10_noise.gif");
	   h1mlnetacoefpl11_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl11_noise.gif");
	   h1mlnetacoefpl12_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl12_noise.gif");
	   h1mlnetacoefpl13_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl13_noise.gif");
	   h1mlnetacoefpl14_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl14_noise.gif");
	   h1mlnetacoefpl15_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl15_noise.gif");
	   h1mlnetacoefpl16_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl16_noise.gif");
	   h1mlnetacoefpl17_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl17_noise.gif");
	   h1mlnetacoefpl18_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl18_noise.gif");
	   h1mlnetacoefpl19_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl19_noise.gif");
	   h1mlnetacoefpl20_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl20_noise.gif");
	   h1mlnetacoefpl21_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl21_noise.gif");
	   h1mlnetacoefpl22_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl22_noise.gif");
	   h1mlnetacoefpl23_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl23_noise.gif");
	   h1mlnetacoefpl24_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl24_noise.gif");
	   h1mlnetacoefpl25_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl25_noise.gif");
	   h1mlnetacoefpl26_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl26_noise.gif");
	   h1mlnetacoefpl27_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl27_noise.gif");
	   h1mlnetacoefpl28_noise->Draw();c2h->Print("GIF/h1mlnetacoefpl28_noise.gif");

 	   h1mlnetacoefmin1_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin1_noise.gif");
	   h1mlnetacoefmin2_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin2_noise.gif");
	   h1mlnetacoefmin3_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin3_noise.gif");
	   h1mlnetacoefmin4_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin4_noise.gif");
	   h1mlnetacoefmin5_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin5_noise.gif");
	   h1mlnetacoefmin6_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin6_noise.gif");
	   h1mlnetacoefmin7_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin7_noise.gif");
	   h1mlnetacoefmin8_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin8_noise.gif");
	   h1mlnetacoefmin9_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin9_noise.gif");
	   h1mlnetacoefmin10_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin10_noise.gif");
	   h1mlnetacoefmin11_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin11_noise.gif");
	   h1mlnetacoefmin12_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin12_noise.gif");
	   h1mlnetacoefmin13_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin13_noise.gif");
	   h1mlnetacoefmin14_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin14_noise.gif");
	   h1mlnetacoefmin15_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin15_noise.gif");
	   h1mlnetacoefmin16_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin16_noise.gif");
	   h1mlnetacoefmin17_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin17_noise.gif");
	   h1mlnetacoefmin18_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin18_noise.gif");
	   h1mlnetacoefmin19_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin19_noise.gif");
	   h1mlnetacoefmin20_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin20_noise.gif");
	   h1mlnetacoefmin21_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin21_noise.gif");
	   h1mlnetacoefmin22_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin22_noise.gif");
	   h1mlnetacoefmin23_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin23_noise.gif");
	   h1mlnetacoefmin24_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin24_noise.gif");
	   h1mlnetacoefmin25_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin25_noise.gif");
	   h1mlnetacoefmin26_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin26_noise.gif");
	   h1mlnetacoefmin27_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin27_noise.gif");
	   h1mlnetacoefmin28_noise->Draw();c2h->Print("GIF/h1mlnetacoefmin28_noise.gif");

	   
 	   h1mlnetacoefpl1->Draw();c2h->Print("GIF/h1mlnetacoefpl1.gif");
	   h1mlnetacoefpl2->Draw();c2h->Print("GIF/h1mlnetacoefpl2.gif");
	   h1mlnetacoefpl3->Draw();c2h->Print("GIF/h1mlnetacoefpl3.gif");
	   h1mlnetacoefpl4->Draw();c2h->Print("GIF/h1mlnetacoefpl4.gif");
	   h1mlnetacoefpl5->Draw();c2h->Print("GIF/h1mlnetacoefpl5.gif");
	   h1mlnetacoefpl6->Draw();c2h->Print("GIF/h1mlnetacoefpl6.gif");
	   h1mlnetacoefpl7->Draw();c2h->Print("GIF/h1mlnetacoefpl7.gif");
	   h1mlnetacoefpl8->Draw();c2h->Print("GIF/h1mlnetacoefpl8.gif");
	   h1mlnetacoefpl9->Draw();c2h->Print("GIF/h1mlnetacoefpl9.gif");
	   h1mlnetacoefpl10->Draw();c2h->Print("GIF/h1mlnetacoefpl10.gif");
	   h1mlnetacoefpl11->Draw();c2h->Print("GIF/h1mlnetacoefpl11.gif");
	   h1mlnetacoefpl12->Draw();c2h->Print("GIF/h1mlnetacoefpl12.gif");
	   h1mlnetacoefpl13->Draw();c2h->Print("GIF/h1mlnetacoefpl13.gif");
	   h1mlnetacoefpl14->Draw();c2h->Print("GIF/h1mlnetacoefpl14.gif");
	   h1mlnetacoefpl15->Draw();c2h->Print("GIF/h1mlnetacoefpl15.gif");
	   h1mlnetacoefpl16->Draw();c2h->Print("GIF/h1mlnetacoefpl16.gif");
	   h1mlnetacoefpl17->Draw();c2h->Print("GIF/h1mlnetacoefpl17.gif");
	   h1mlnetacoefpl18->Draw();c2h->Print("GIF/h1mlnetacoefpl18.gif");
	   h1mlnetacoefpl19->Draw();c2h->Print("GIF/h1mlnetacoefpl19.gif");
	   h1mlnetacoefpl20->Draw();c2h->Print("GIF/h1mlnetacoefpl20.gif");
	   h1mlnetacoefpl21->Draw();c2h->Print("GIF/h1mlnetacoefpl21.gif");
 	   h1mlnetacoefpl22->Draw();c2h->Print("GIF/h1mlnetacoefpl22.gif");
	   h1mlnetacoefpl23->Draw();c2h->Print("GIF/h1mlnetacoefpl23.gif");
	   h1mlnetacoefpl24->Draw();c2h->Print("GIF/h1mlnetacoefpl24.gif");
	   h1mlnetacoefpl25->Draw();c2h->Print("GIF/h1mlnetacoefpl25.gif");
	   h1mlnetacoefpl26->Draw();c2h->Print("GIF/h1mlnetacoefpl26.gif");
	   h1mlnetacoefpl27->Draw();c2h->Print("GIF/h1mlnetacoefpl27.gif");
	   h1mlnetacoefpl28->Draw();c2h->Print("GIF/h1mlnetacoefpl28.gif");
	   
	   
 	   h1mlnetacoefmin1->Draw();c2h->Print("GIF/h1mlnetacoefmin1.gif");
	   h1mlnetacoefmin2->Draw();c2h->Print("GIF/h1mlnetacoefmin2.gif");
	   h1mlnetacoefmin3->Draw();c2h->Print("GIF/h1mlnetacoefmin3.gif");
	   h1mlnetacoefmin4->Draw();c2h->Print("GIF/h1mlnetacoefmin4.gif");
	   h1mlnetacoefmin5->Draw();c2h->Print("GIF/h1mlnetacoefmin5.gif");
	   h1mlnetacoefmin6->Draw();c2h->Print("GIF/h1mlnetacoefmin6.gif");
	   h1mlnetacoefmin7->Draw();c2h->Print("GIF/h1mlnetacoefmin7.gif");
	   h1mlnetacoefmin8->Draw();c2h->Print("GIF/h1mlnetacoefmin8.gif");
	   h1mlnetacoefmin9->Draw();c2h->Print("GIF/h1mlnetacoefmin9.gif");
	   h1mlnetacoefmin10->Draw();c2h->Print("GIF/h1mlnetacoefmin10.gif");
	   h1mlnetacoefmin11->Draw();c2h->Print("GIF/h1mlnetacoefmin11.gif");
	   h1mlnetacoefmin12->Draw();c2h->Print("GIF/h1mlnetacoefmin12.gif");
	   h1mlnetacoefmin13->Draw();c2h->Print("GIF/h1mlnetacoefmin13.gif");
	   h1mlnetacoefmin14->Draw();c2h->Print("GIF/h1mlnetacoefmin14.gif");
	   h1mlnetacoefmin15->Draw();c2h->Print("GIF/h1mlnetacoefmin15.gif");
	   h1mlnetacoefmin16->Draw();c2h->Print("GIF/h1mlnetacoefmin16.gif");
	   h1mlnetacoefmin17->Draw();c2h->Print("GIF/h1mlnetacoefmin17.gif");
	   h1mlnetacoefmin18->Draw();c2h->Print("GIF/h1mlnetacoefmin18.gif");
	   h1mlnetacoefmin19->Draw();c2h->Print("GIF/h1mlnetacoefmin19.gif");
	   h1mlnetacoefmin20->Draw();c2h->Print("GIF/h1mlnetacoefmin20.gif");
	   h1mlnetacoefmin21->Draw();c2h->Print("GIF/h1mlnetacoefmin21.gif");
 	   h1mlnetacoefmin22->Draw();c2h->Print("GIF/h1mlnetacoefmin22.gif");
	   h1mlnetacoefmin23->Draw();c2h->Print("GIF/h1mlnetacoefmin23.gif");
	   h1mlnetacoefmin24->Draw();c2h->Print("GIF/h1mlnetacoefmin24.gif");
	   h1mlnetacoefmin25->Draw();c2h->Print("GIF/h1mlnetacoefmin25.gif");
	   h1mlnetacoefmin26->Draw();c2h->Print("GIF/h1mlnetacoefmin26.gif");
	   h1mlnetacoefmin27->Draw();c2h->Print("GIF/h1mlnetacoefmin27.gif");
	   h1mlnetacoefmin28->Draw();c2h->Print("GIF/h1mlnetacoefmin28.gif");
	   
	   
	   
	   
           h1mlnetacoefpl2D1->Draw("box");c2h->Print("GIF/h1mlnetacoefplD1.gif");
           h1mlnetacoefpl2D1_noise->Draw("box");c2h->Print("GIF/h1mlnetacoefplD1_noise.gif");
           h1mlnetacoefmin2D1->Draw("box");c2h->Print("GIF/h1mlnetacoefminD1.gif");
           h1mlnetacoefmin2D1_noise->Draw("box");c2h->Print("GIF/h1mlnetacoefminD1_noise.gif");
  
    TFile f0("coefficients_2mln.root");  
  
 	   h2mlnetacoefpl1->Draw();c2h->Print("GIF/h2mlnetacoefpl1.gif");
	   h2mlnetacoefpl2->Draw();c2h->Print("GIF/h2mlnetacoefpl2.gif");
	   h2mlnetacoefpl3->Draw();c2h->Print("GIF/h2mlnetacoefpl3.gif");
	   h2mlnetacoefpl4->Draw();c2h->Print("GIF/h2mlnetacoefpl4.gif");
	   h2mlnetacoefpl5->Draw();c2h->Print("GIF/h2mlnetacoefpl5.gif");
	   h2mlnetacoefpl6->Draw();c2h->Print("GIF/h2mlnetacoefpl6.gif");
	   h2mlnetacoefpl7->Draw();c2h->Print("GIF/h2mlnetacoefpl7.gif");
	   h2mlnetacoefpl8->Draw();c2h->Print("GIF/h2mlnetacoefpl8.gif");
	   h2mlnetacoefpl9->Draw();c2h->Print("GIF/h2mlnetacoefpl9.gif");
	   h2mlnetacoefpl10->Draw();c2h->Print("GIF/h2mlnetacoefpl10.gif");
	   h2mlnetacoefpl11->Draw();c2h->Print("GIF/h2mlnetacoefpl11.gif");
	   h2mlnetacoefpl12->Draw();c2h->Print("GIF/h2mlnetacoefpl12.gif");
	   h2mlnetacoefpl13->Draw();c2h->Print("GIF/h2mlnetacoefpl13.gif");
	   h2mlnetacoefpl14->Draw();c2h->Print("GIF/h2mlnetacoefpl14.gif");
	   h2mlnetacoefpl15->Draw();c2h->Print("GIF/h2mlnetacoefpl15.gif");
	   h2mlnetacoefpl16->Draw();c2h->Print("GIF/h2mlnetacoefpl16.gif");
	   h2mlnetacoefpl17->Draw();c2h->Print("GIF/h2mlnetacoefpl17.gif");
	   h2mlnetacoefpl18->Draw();c2h->Print("GIF/h2mlnetacoefpl18.gif");
	   h2mlnetacoefpl19->Draw();c2h->Print("GIF/h2mlnetacoefpl19.gif");
	   h2mlnetacoefpl20->Draw();c2h->Print("GIF/h2mlnetacoefpl20.gif");
	   h2mlnetacoefpl21->Draw();c2h->Print("GIF/h2mlnetacoefpl21.gif");
 	   h2mlnetacoefpl22->Draw();c2h->Print("GIF/h2mlnetacoefpl22.gif");
	   h2mlnetacoefpl23->Draw();c2h->Print("GIF/h2mlnetacoefpl23.gif");
	   h2mlnetacoefpl24->Draw();c2h->Print("GIF/h2mlnetacoefpl24.gif");
	   h2mlnetacoefpl25->Draw();c2h->Print("GIF/h2mlnetacoefpl25.gif");
	   h2mlnetacoefpl26->Draw();c2h->Print("GIF/h2mlnetacoefpl26.gif");
	   h2mlnetacoefpl27->Draw();c2h->Print("GIF/h2mlnetacoefpl27.gif");
	   h2mlnetacoefpl28->Draw();c2h->Print("GIF/h2mlnetacoefpl28.gif");

 	   h2mlnetacoefmin1->Draw();c2h->Print("GIF/h2mlnetacoefmin1.gif");
	   h2mlnetacoefmin2->Draw();c2h->Print("GIF/h2mlnetacoefmin2.gif");
	   h2mlnetacoefmin3->Draw();c2h->Print("GIF/h2mlnetacoefmin3.gif");
	   h2mlnetacoefmin4->Draw();c2h->Print("GIF/h2mlnetacoefmin4.gif");
	   h2mlnetacoefmin5->Draw();c2h->Print("GIF/h2mlnetacoefmin5.gif");
	   h2mlnetacoefmin6->Draw();c2h->Print("GIF/h2mlnetacoefmin6.gif");
	   h2mlnetacoefmin7->Draw();c2h->Print("GIF/h2mlnetacoefmin7.gif");
	   h2mlnetacoefmin8->Draw();c2h->Print("GIF/h2mlnetacoefmin8.gif");
	   h2mlnetacoefmin9->Draw();c2h->Print("GIF/h2mlnetacoefmin9.gif");
	   h2mlnetacoefmin10->Draw();c2h->Print("GIF/h2mlnetacoefmin10.gif");
	   h2mlnetacoefmin11->Draw();c2h->Print("GIF/h2mlnetacoefmin11.gif");
	   h2mlnetacoefmin12->Draw();c2h->Print("GIF/h2mlnetacoefmin12.gif");
	   h2mlnetacoefmin13->Draw();c2h->Print("GIF/h2mlnetacoefmin13.gif");
	   h2mlnetacoefmin14->Draw();c2h->Print("GIF/h2mlnetacoefmin14.gif");
	   h2mlnetacoefmin15->Draw();c2h->Print("GIF/h2mlnetacoefmin15.gif");
	   h2mlnetacoefmin16->Draw();c2h->Print("GIF/h2mlnetacoefmin16.gif");
	   h2mlnetacoefmin17->Draw();c2h->Print("GIF/h2mlnetacoefmin17.gif");
	   h2mlnetacoefmin18->Draw();c2h->Print("GIF/h2mlnetacoefmin18.gif");
	   h2mlnetacoefmin19->Draw();c2h->Print("GIF/h2mlnetacoefmin19.gif");
	   h2mlnetacoefmin20->Draw();c2h->Print("GIF/h2mlnetacoefmin20.gif");
	   h2mlnetacoefmin21->Draw();c2h->Print("GIF/h2mlnetacoefmin21.gif");
 	   h2mlnetacoefmin22->Draw();c2h->Print("GIF/h2mlnetacoefmin22.gif");
	   h2mlnetacoefmin23->Draw();c2h->Print("GIF/h2mlnetacoefmin23.gif");
	   h2mlnetacoefmin24->Draw();c2h->Print("GIF/h2mlnetacoefmin24.gif");
	   h2mlnetacoefmin25->Draw();c2h->Print("GIF/h2mlnetacoefmin25.gif");
	   h2mlnetacoefmin26->Draw();c2h->Print("GIF/h2mlnetacoefmin26.gif");
	   h2mlnetacoefmin27->Draw();c2h->Print("GIF/h2mlnetacoefmin27.gif");
	   h2mlnetacoefmin28->Draw();c2h->Print("GIF/h2mlnetacoefmin28.gif");
	   
	   
           h2mlnetacoefpl2D1->Draw("box");c2h->Print("GIF/h2mlnetacoefplD1.gif");
           h2mlnetacoefpl2D1_noise->Draw("box");c2h->Print("GIF/h2mlnetacoefplD1_noise.gif");
           h2mlnetacoefmin2D1->Draw("box");c2h->Print("GIF/h2mlnetacoefminD1.gif");
           h2mlnetacoefmin2D1_noise->Draw("box");c2h->Print("GIF/h2mlnetacoefminD1_noise.gif");
	   
           TFile f0("coefficients_3mln.root");  
  
 	   h3mlnetacoefpl1->Draw();c2h->Print("GIF/h3mlnetacoefpl1.gif");
	   h3mlnetacoefpl2->Draw();c2h->Print("GIF/h3mlnetacoefpl2.gif");
	   h3mlnetacoefpl3->Draw();c2h->Print("GIF/h3mlnetacoefpl3.gif");
	   h3mlnetacoefpl4->Draw();c2h->Print("GIF/h3mlnetacoefpl4.gif");
	   h3mlnetacoefpl5->Draw();c2h->Print("GIF/h3mlnetacoefpl5.gif");
	   h3mlnetacoefpl6->Draw();c2h->Print("GIF/h3mlnetacoefpl6.gif");
	   h3mlnetacoefpl7->Draw();c2h->Print("GIF/h3mlnetacoefpl7.gif");
	   h3mlnetacoefpl8->Draw();c2h->Print("GIF/h3mlnetacoefpl8.gif");
	   h3mlnetacoefpl9->Draw();c2h->Print("GIF/h3mlnetacoefpl9.gif");
	   h3mlnetacoefpl10->Draw();c2h->Print("GIF/h3mlnetacoefpl10.gif");
	   h3mlnetacoefpl11->Draw();c2h->Print("GIF/h3mlnetacoefpl11.gif");
	   h3mlnetacoefpl12->Draw();c2h->Print("GIF/h3mlnetacoefpl12.gif");
	   h3mlnetacoefpl13->Draw();c2h->Print("GIF/h3mlnetacoefpl13.gif");
	   h3mlnetacoefpl14->Draw();c2h->Print("GIF/h3mlnetacoefpl14.gif");
	   h3mlnetacoefpl15->Draw();c2h->Print("GIF/h3mlnetacoefpl15.gif");
	   h3mlnetacoefpl16->Draw();c2h->Print("GIF/h3mlnetacoefpl16.gif");
	   h3mlnetacoefpl17->Draw();c2h->Print("GIF/h3mlnetacoefpl17.gif");
	   h3mlnetacoefpl18->Draw();c2h->Print("GIF/h3mlnetacoefpl18.gif");
	   h3mlnetacoefpl19->Draw();c2h->Print("GIF/h3mlnetacoefpl19.gif");
	   h3mlnetacoefpl20->Draw();c2h->Print("GIF/h3mlnetacoefpl20.gif");
	   h3mlnetacoefpl21->Draw();c2h->Print("GIF/h3mlnetacoefpl21.gif");
 	   h3mlnetacoefpl22->Draw();c2h->Print("GIF/h3mlnetacoefpl22.gif");
	   h3mlnetacoefpl23->Draw();c2h->Print("GIF/h3mlnetacoefpl23.gif");
	   h3mlnetacoefpl24->Draw();c2h->Print("GIF/h3mlnetacoefpl24.gif");
	   h3mlnetacoefpl25->Draw();c2h->Print("GIF/h3mlnetacoefpl25.gif");
	   h3mlnetacoefpl26->Draw();c2h->Print("GIF/h3mlnetacoefpl26.gif");
	   h3mlnetacoefpl27->Draw();c2h->Print("GIF/h3mlnetacoefpl27.gif");
	   h3mlnetacoefpl28->Draw();c2h->Print("GIF/h3mlnetacoefpl28.gif");
	   
 	   h3mlnetacoefmin1->Draw();c2h->Print("GIF/h3mlnetacoefmin1.gif");
	   h3mlnetacoefmin2->Draw();c2h->Print("GIF/h3mlnetacoefmin2.gif");
	   h3mlnetacoefmin3->Draw();c2h->Print("GIF/h3mlnetacoefmin3.gif");
	   h3mlnetacoefmin4->Draw();c2h->Print("GIF/h3mlnetacoefmin4.gif");
	   h3mlnetacoefmin5->Draw();c2h->Print("GIF/h3mlnetacoefmin5.gif");
	   h3mlnetacoefmin6->Draw();c2h->Print("GIF/h3mlnetacoefmin6.gif");
	   h3mlnetacoefmin7->Draw();c2h->Print("GIF/h3mlnetacoefmin7.gif");
	   h3mlnetacoefmin8->Draw();c2h->Print("GIF/h3mlnetacoefmin8.gif");
	   h3mlnetacoefmin9->Draw();c2h->Print("GIF/h3mlnetacoefmin9.gif");
	   h3mlnetacoefmin10->Draw();c2h->Print("GIF/h3mlnetacoefmin10.gif");
	   h3mlnetacoefmin11->Draw();c2h->Print("GIF/h3mlnetacoefmin11.gif");
	   h3mlnetacoefmin12->Draw();c2h->Print("GIF/h3mlnetacoefmin12.gif");
	   h3mlnetacoefmin13->Draw();c2h->Print("GIF/h3mlnetacoefmin13.gif");
	   h3mlnetacoefmin14->Draw();c2h->Print("GIF/h3mlnetacoefmin14.gif");
	   h3mlnetacoefmin15->Draw();c2h->Print("GIF/h3mlnetacoefmin15.gif");
	   h3mlnetacoefmin16->Draw();c2h->Print("GIF/h3mlnetacoefmin16.gif");
	   h3mlnetacoefmin17->Draw();c2h->Print("GIF/h3mlnetacoefmin17.gif");
	   h3mlnetacoefmin18->Draw();c2h->Print("GIF/h3mlnetacoefmin18.gif");
	   h3mlnetacoefmin19->Draw();c2h->Print("GIF/h3mlnetacoefmin19.gif");
	   h3mlnetacoefmin20->Draw();c2h->Print("GIF/h3mlnetacoefmin20.gif");
	   h3mlnetacoefmin21->Draw();c2h->Print("GIF/h3mlnetacoefmin21.gif");
 	   h3mlnetacoefmin22->Draw();c2h->Print("GIF/h3mlnetacoefmin22.gif");
	   h3mlnetacoefmin23->Draw();c2h->Print("GIF/h3mlnetacoefmin23.gif");
	   h3mlnetacoefmin24->Draw();c2h->Print("GIF/h3mlnetacoefmin24.gif");
	   h3mlnetacoefmin25->Draw();c2h->Print("GIF/h3mlnetacoefmin25.gif");
	   h3mlnetacoefmin26->Draw();c2h->Print("GIF/h3mlnetacoefmin26.gif");
	   h3mlnetacoefmin27->Draw();c2h->Print("GIF/h3mlnetacoefmin27.gif");
	   h3mlnetacoefmin28->Draw();c2h->Print("GIF/h3mlnetacoefmin28.gif");
	   
	   
           h3mlnetacoefpl2D1->Draw("box");c2h->Print("GIF/h3mlnetacoefplD1.gif");
           h3mlnetacoefpl2D1_noise->Draw("box");c2h->Print("GIF/h3mlnetacoefplD1_noise.gif");
           h3mlnetacoefmin2D1->Draw("box");c2h->Print("GIF/h3mlnetacoefminD1.gif");
           h3mlnetacoefmin2D1_noise->Draw("box");c2h->Print("GIF/h3mlnetacoefminD1_noise.gif");
	   
           TFile f0("coefficients_6mln.root");  
  
 	   h6mlnetacoefpl1->Draw();c2h->Print("GIF/h6mlnetacoefpl1.gif");
	   h6mlnetacoefpl2->Draw();c2h->Print("GIF/h6mlnetacoefpl2.gif");
	   h6mlnetacoefpl3->Draw();c2h->Print("GIF/h6mlnetacoefpl3.gif");
	   h6mlnetacoefpl4->Draw();c2h->Print("GIF/h6mlnetacoefpl4.gif");
	   h6mlnetacoefpl5->Draw();c2h->Print("GIF/h6mlnetacoefpl5.gif");
	   h6mlnetacoefpl6->Draw();c2h->Print("GIF/h6mlnetacoefpl6.gif");
	   h6mlnetacoefpl7->Draw();c2h->Print("GIF/h6mlnetacoefpl7.gif");
	   h6mlnetacoefpl8->Draw();c2h->Print("GIF/h6mlnetacoefpl8.gif");
	   h6mlnetacoefpl9->Draw();c2h->Print("GIF/h6mlnetacoefpl9.gif");
	   h6mlnetacoefpl10->Draw();c2h->Print("GIF/h6mlnetacoefpl10.gif");
	   h6mlnetacoefpl11->Draw();c2h->Print("GIF/h6mlnetacoefpl11.gif");
	   h6mlnetacoefpl12->Draw();c2h->Print("GIF/h6mlnetacoefpl12.gif");
	   h6mlnetacoefpl13->Draw();c2h->Print("GIF/h6mlnetacoefpl13.gif");
	   h6mlnetacoefpl14->Draw();c2h->Print("GIF/h6mlnetacoefpl14.gif");
	   h6mlnetacoefpl15->Draw();c2h->Print("GIF/h6mlnetacoefpl15.gif");
	   h6mlnetacoefpl16_HB->Draw();c2h->Print("GIF/h6mlnetacoefpl16_HB.gif");
	   h6mlnetacoefpl16_HE->Draw();c2h->Print("GIF/h6mlnetacoefpl16_HE.gif");
	   h6mlnetacoefpl17->Draw();c2h->Print("GIF/h6mlnetacoefpl17.gif");
	   h6mlnetacoefpl18->Draw();c2h->Print("GIF/h6mlnetacoefpl18.gif");
	   h6mlnetacoefpl19->Draw();c2h->Print("GIF/h6mlnetacoefpl19.gif");
	   h6mlnetacoefpl20->Draw();c2h->Print("GIF/h6mlnetacoefpl20.gif");
	   h6mlnetacoefpl21->Draw();c2h->Print("GIF/h6mlnetacoefpl21.gif");
 	   h6mlnetacoefpl22->Draw();c2h->Print("GIF/h6mlnetacoefpl22.gif");
	   h6mlnetacoefpl23->Draw();c2h->Print("GIF/h6mlnetacoefpl23.gif");
	   h6mlnetacoefpl24->Draw();c2h->Print("GIF/h6mlnetacoefpl24.gif");
	   h6mlnetacoefpl25->Draw();c2h->Print("GIF/h6mlnetacoefpl25.gif");
	   h6mlnetacoefpl26->Draw();c2h->Print("GIF/h6mlnetacoefpl26.gif");
	   h6mlnetacoefpl27->Draw();c2h->Print("GIF/h6mlnetacoefpl27.gif");
	   h6mlnetacoefpl28->Draw();c2h->Print("GIF/h6mlnetacoefpl28.gif");
	   h6mlnetacoefpl29->Draw();c2h->Print("GIF/h6mlnetacoefpl29.gif");
	   
 	   h6mlnetacoefmin1->Draw();c2h->Print("GIF/h6mlnetacoefmin1.gif");
	   h6mlnetacoefmin2->Draw();c2h->Print("GIF/h6mlnetacoefmin2.gif");
	   h6mlnetacoefmin3->Draw();c2h->Print("GIF/h6mlnetacoefmin3.gif");
	   h6mlnetacoefmin4->Draw();c2h->Print("GIF/h6mlnetacoefmin4.gif");
	   h6mlnetacoefmin5->Draw();c2h->Print("GIF/h6mlnetacoefmin5.gif");
	   h6mlnetacoefmin6->Draw();c2h->Print("GIF/h6mlnetacoefmin6.gif");
	   h6mlnetacoefmin7->Draw();c2h->Print("GIF/h6mlnetacoefmin7.gif");
	   h6mlnetacoefmin8->Draw();c2h->Print("GIF/h6mlnetacoefmin8.gif");
	   h6mlnetacoefmin9->Draw();c2h->Print("GIF/h6mlnetacoefmin9.gif");
	   h6mlnetacoefmin10->Draw();c2h->Print("GIF/h6mlnetacoefmin10.gif");
	   h6mlnetacoefmin11->Draw();c2h->Print("GIF/h6mlnetacoefmin11.gif");
	   h6mlnetacoefmin12->Draw();c2h->Print("GIF/h6mlnetacoefmin12.gif");
	   h6mlnetacoefmin13->Draw();c2h->Print("GIF/h6mlnetacoefmin13.gif");
	   h6mlnetacoefmin14->Draw();c2h->Print("GIF/h6mlnetacoefmin14.gif");
	   h6mlnetacoefmin15->Draw();c2h->Print("GIF/h6mlnetacoefmin15.gif");
	   h6mlnetacoefmin16_HB->Draw();c2h->Print("GIF/h6mlnetacoefmin16_HB.gif");
	   h6mlnetacoefmin16_HE->Draw();c2h->Print("GIF/h6mlnetacoefmin16_HE.gif");
	   h6mlnetacoefmin17->Draw();c2h->Print("GIF/h6mlnetacoefmin17.gif");
	   h6mlnetacoefmin18->Draw();c2h->Print("GIF/h6mlnetacoefmin18.gif");
	   h6mlnetacoefmin19->Draw();c2h->Print("GIF/h6mlnetacoefmin19.gif");
	   h6mlnetacoefmin20->Draw();c2h->Print("GIF/h6mlnetacoefmin20.gif");
	   h6mlnetacoefmin21->Draw();c2h->Print("GIF/h6mlnetacoefmin21.gif");
 	   h6mlnetacoefmin22->Draw();c2h->Print("GIF/h6mlnetacoefmin22.gif");
	   h6mlnetacoefmin23->Draw();c2h->Print("GIF/h6mlnetacoefmin23.gif");
	   h6mlnetacoefmin24->Draw();c2h->Print("GIF/h6mlnetacoefmin24.gif");
	   h6mlnetacoefmin25->Draw();c2h->Print("GIF/h6mlnetacoefmin25.gif");
	   h6mlnetacoefmin26->Draw();c2h->Print("GIF/h6mlnetacoefmin26.gif");
	   h6mlnetacoefmin27->Draw();c2h->Print("GIF/h6mlnetacoefmin27.gif");
	   h6mlnetacoefmin28->Draw();c2h->Print("GIF/h6mlnetacoefmin28.gif");
	   h6mlnetacoefmin29->Draw();c2h->Print("GIF/h6mlnetacoefmin29.gif");
	   
	   
           h6mlnetacoefpl2D1->Draw("box");c2h->Print("GIF/h6mlnetacoefplD1.gif");
           h6mlnetacoefpl2D1_noise->Draw("box");c2h->Print("GIF/h6mlnetacoefplD1_noise.gif");
           h6mlnetacoefmin2D1->Draw("box");c2h->Print("GIF/h6mlnetacoefminD1.gif");
           h6mlnetacoefmin2D1_noise->Draw("box");c2h->Print("GIF/h6mlnetacoefminD1_noise.gif");
	   
           h6mlnetacoefpl2D16->Draw("box");c2h->Print("GIF/h6mlnetacoefplD16.gif");
           h6mlnetacoefpl2D16_noise->Draw("box");c2h->Print("GIF/h6mlnetacoefplD16_noise.gif");
           h6mlnetacoefmin2D16->Draw("box");c2h->Print("GIF/h6mlnetacoefminD16.gif");
           h6mlnetacoefmin2D16_noise->Draw("box");c2h->Print("GIF/h6mlnetacoefminD16_noise.gif");

           TFile f0("coefficients_12mln.root");  
  
 	   h12mlnetacoefpl1->Draw();c2h->Print("GIF/h12mlnetacoefpl1.gif");
	   h12mlnetacoefpl2->Draw();c2h->Print("GIF/h12mlnetacoefpl2.gif");
	   h12mlnetacoefpl3->Draw();c2h->Print("GIF/h12mlnetacoefpl3.gif");
	   h12mlnetacoefpl4->Draw();c2h->Print("GIF/h12mlnetacoefpl4.gif");
	   h12mlnetacoefpl5->Draw();c2h->Print("GIF/h12mlnetacoefpl5.gif");
	   h12mlnetacoefpl6->Draw();c2h->Print("GIF/h12mlnetacoefpl6.gif");
	   h12mlnetacoefpl7->Draw();c2h->Print("GIF/h12mlnetacoefpl7.gif");
	   h12mlnetacoefpl8->Draw();c2h->Print("GIF/h12mlnetacoefpl8.gif");
	   h12mlnetacoefpl9->Draw();c2h->Print("GIF/h12mlnetacoefpl9.gif");
	   h12mlnetacoefpl10->Draw();c2h->Print("GIF/h12mlnetacoefpl10.gif");
	   h12mlnetacoefpl11->Draw();c2h->Print("GIF/h12mlnetacoefpl11.gif");
	   h12mlnetacoefpl12->Draw();c2h->Print("GIF/h12mlnetacoefpl12.gif");
	   h12mlnetacoefpl13->Draw();c2h->Print("GIF/h12mlnetacoefpl13.gif");
	   h12mlnetacoefpl14->Draw();c2h->Print("GIF/h12mlnetacoefpl14.gif");
	   h12mlnetacoefpl15->Draw();c2h->Print("GIF/h12mlnetacoefpl15.gif");
	   h12mlnetacoefpl16_HB->Draw();c2h->Print("GIF/h12mlnetacoefpl16_HB.gif");
	   h12mlnetacoefpl16_HE->Draw();c2h->Print("GIF/h12mlnetacoefpl16_HE.gif");
	   h12mlnetacoefpl17->Draw();c2h->Print("GIF/h12mlnetacoefpl17.gif");
	   h12mlnetacoefpl18->Draw();c2h->Print("GIF/h12mlnetacoefpl18.gif");
	   h12mlnetacoefpl19->Draw();c2h->Print("GIF/h12mlnetacoefpl19.gif");
	   h12mlnetacoefpl20->Draw();c2h->Print("GIF/h12mlnetacoefpl20.gif");
	   h12mlnetacoefpl21->Draw();c2h->Print("GIF/h12mlnetacoefpl21.gif");
 	   h12mlnetacoefpl22->Draw();c2h->Print("GIF/h12mlnetacoefpl22.gif");
	   h12mlnetacoefpl23->Draw();c2h->Print("GIF/h12mlnetacoefpl23.gif");
	   h12mlnetacoefpl24->Draw();c2h->Print("GIF/h12mlnetacoefpl24.gif");
	   h12mlnetacoefpl25->Draw();c2h->Print("GIF/h12mlnetacoefpl25.gif");
	   h12mlnetacoefpl26->Draw();c2h->Print("GIF/h12mlnetacoefpl26.gif");
	   h12mlnetacoefpl27->Draw();c2h->Print("GIF/h12mlnetacoefpl27.gif");
	   h12mlnetacoefpl28->Draw();c2h->Print("GIF/h12mlnetacoefpl28.gif");
	   h12mlnetacoefpl29->Draw();c2h->Print("GIF/h12mlnetacoefpl29.gif");
	   
 	   h12mlnetacoefmin1->Draw();c2h->Print("GIF/h12mlnetacoefmin1.gif");
	   h12mlnetacoefmin2->Draw();c2h->Print("GIF/h12mlnetacoefmin2.gif");
	   h12mlnetacoefmin3->Draw();c2h->Print("GIF/h12mlnetacoefmin3.gif");
	   h12mlnetacoefmin4->Draw();c2h->Print("GIF/h12mlnetacoefmin4.gif");
	   h12mlnetacoefmin5->Draw();c2h->Print("GIF/h12mlnetacoefmin5.gif");
	   h12mlnetacoefmin6->Draw();c2h->Print("GIF/h12mlnetacoefmin6.gif");
	   h12mlnetacoefmin7->Draw();c2h->Print("GIF/h12mlnetacoefmin7.gif");
	   h12mlnetacoefmin8->Draw();c2h->Print("GIF/h12mlnetacoefmin8.gif");
	   h12mlnetacoefmin9->Draw();c2h->Print("GIF/h12mlnetacoefmin9.gif");
	   h12mlnetacoefmin10->Draw();c2h->Print("GIF/h12mlnetacoefmin10.gif");
	   h12mlnetacoefmin11->Draw();c2h->Print("GIF/h12mlnetacoefmin11.gif");
	   h12mlnetacoefmin12->Draw();c2h->Print("GIF/h12mlnetacoefmin12.gif");
	   h12mlnetacoefmin13->Draw();c2h->Print("GIF/h12mlnetacoefmin13.gif");
	   h12mlnetacoefmin14->Draw();c2h->Print("GIF/h12mlnetacoefmin14.gif");
	   h12mlnetacoefmin15->Draw();c2h->Print("GIF/h12mlnetacoefmin15.gif");
	   h12mlnetacoefmin16_HB->Draw();c2h->Print("GIF/h12mlnetacoefmin16_HB.gif");
	   h12mlnetacoefmin16_HE->Draw();c2h->Print("GIF/h12mlnetacoefmin16_HE.gif");
	   h12mlnetacoefmin17->Draw();c2h->Print("GIF/h12mlnetacoefmin17.gif");
	   h12mlnetacoefmin18->Draw();c2h->Print("GIF/h12mlnetacoefmin18.gif");
	   h12mlnetacoefmin19->Draw();c2h->Print("GIF/h12mlnetacoefmin19.gif");
	   h12mlnetacoefmin20->Draw();c2h->Print("GIF/h12mlnetacoefmin20.gif");
	   h12mlnetacoefmin21->Draw();c2h->Print("GIF/h12mlnetacoefmin21.gif");
 	   h12mlnetacoefmin22->Draw();c2h->Print("GIF/h12mlnetacoefmin22.gif");
	   h12mlnetacoefmin23->Draw();c2h->Print("GIF/h12mlnetacoefmin23.gif");
	   h12mlnetacoefmin24->Draw();c2h->Print("GIF/h12mlnetacoefmin24.gif");
	   h12mlnetacoefmin25->Draw();c2h->Print("GIF/h12mlnetacoefmin25.gif");
	   h12mlnetacoefmin26->Draw();c2h->Print("GIF/h12mlnetacoefmin26.gif");
	   h12mlnetacoefmin27->Draw();c2h->Print("GIF/h12mlnetacoefmin27.gif");
	   h12mlnetacoefmin28->Draw();c2h->Print("GIF/h12mlnetacoefmin28.gif");
	   h12mlnetacoefmin29->Draw();c2h->Print("GIF/h12mlnetacoefmin29.gif");
	   
	   
           h12mlnetacoefpl2D1->Draw("box");c2h->Print("GIF/h12mlnetacoefplD1.gif");
           h12mlnetacoefpl2D1_noise->Draw("box");c2h->Print("GIF/h12mlnetacoefplD1_noise.gif");
           h12mlnetacoefmin2D1->Draw("box");c2h->Print("GIF/h12mlnetacoefminD1.gif");
           h12mlnetacoefmin2D1_noise->Draw("box");c2h->Print("GIF/h12mlnetacoefminD1_noise.gif");
	   
           h12mlnetacoefpl2D16->Draw("box");c2h->Print("GIF/h12mlnetacoefplD16.gif");
           h12mlnetacoefpl2D16_noise->Draw("box");c2h->Print("GIF/h12mlnetacoefplD16_noise.gif");
           h12mlnetacoefmin2D16->Draw("box");c2h->Print("GIF/h12mlnetacoefminD16.gif");
           h12mlnetacoefmin2D16_noise->Draw("box");c2h->Print("GIF/h12mlnetacoefminD16_noise.gif");
  
}
